import type { UiLanguage } from "@/localization/i18n";

type Copy = Record<UiLanguage, string>;

const copy = (en: string, zh: string, es: string, fr: string, de: string, ja: string, ko: string, pt: string): Copy => ({
  en, "zh-CN": zh, es, fr, de, ja, ko, pt,
});

const UI_COPY: Record<string, Copy> = {
  "Try again": copy("Try again", "重试", "Reintentar", "Réessayer", "Erneut versuchen", "もう一度試す", "다시 시도", "Tentar novamente"),
  Workspaces: copy("Workspaces", "工作区", "Espacios", "Espaces", "Arbeitsbereiche", "ワークスペース", "작업 공간", "Espaços"),
  "Browse and organize your saved notes.": copy("Browse and organize your saved notes.", "浏览并整理已保存的笔记。", "Explora y organiza tus notas guardadas.", "Parcourez et organisez vos notes enregistrées.", "Gespeicherte Notizen durchsuchen und organisieren.", "保存したノートを閲覧・整理します。", "저장된 노트를 찾아보고 정리하세요.", "Explore e organize as notas guardadas."),
  "Start a transcription": copy("Start a transcription", "开始转写", "Iniciar una transcripción", "Démarrer une transcription", "Transkription starten", "文字起こしを開始", "전사 시작", "Iniciar uma transcrição"),
  "Choose live recording or upload an audio file.": copy("Choose live recording or upload an audio file.", "选择实时录音或上传音频文件。", "Elige grabación en directo o sube un archivo de audio.", "Choisissez l’enregistrement en direct ou importez un fichier audio.", "Live-Aufnahme wählen oder Audiodatei hochladen.", "ライブ録音または音声ファイルを選択します。", "실시간 녹음 또는 오디오 파일 업로드를 선택하세요.", "Escolha gravação em direto ou carregue um ficheiro de áudio."),
  "Live recording": copy("Live recording", "实时录音", "Grabación en directo", "Enregistrement en direct", "Live-Aufnahme", "ライブ録音", "실시간 녹음", "Gravação em direto"),
  "Record and transcribe as you speak.": copy("Record and transcribe as you speak.", "边说边录音和转写。", "Graba y transcribe mientras hablas.", "Enregistrez et transcrivez pendant que vous parlez.", "Beim Sprechen aufnehmen und transkribieren.", "話しながら録音・文字起こしします。", "말하면서 녹음하고 전사하세요.", "Grave e transcreva enquanto fala."),
  "Upload audio": copy("Upload audio", "上传音频", "Subir audio", "Importer un audio", "Audio hochladen", "音声をアップロード", "오디오 업로드", "Carregar áudio"),
  "Choose a file and start transcribing.": copy("Choose a file and start transcribing.", "选择文件并开始转写。", "Elige un archivo y empieza a transcribir.", "Choisissez un fichier et lancez la transcription.", "Datei wählen und Transkription starten.", "ファイルを選択して文字起こしを開始します。", "파일을 선택하고 전사를 시작하세요.", "Escolha um ficheiro e comece a transcrever."),
  Overview: copy("Overview", "概览", "Resumen", "Aperçu", "Übersicht", "概要", "개요", "Visão geral"),
  "Your notes and upcoming moments at a glance.": copy("Your notes and upcoming moments at a glance.", "一览笔记和即将到来的事项。", "Tus notas y próximos momentos de un vistazo.", "Vos notes et événements à venir en un coup d’œil.", "Notizen und anstehende Termine auf einen Blick.", "ノートと今後の予定を一覧できます。", "노트와 예정된 일정을 한눈에 확인하세요.", "As suas notas e próximos momentos num relance."),
  Notes: copy("Notes", "笔记", "Notas", "Notes", "Notizen", "ノート", "노트", "Notas"),
  Calendar: copy("Calendar", "日历", "Calendario", "Calendrier", "Kalender", "カレンダー", "캘린더", "Calendário"),
  "No calendar items for this date.": copy("No calendar items for this date.", "该日期没有日历事项。", "No hay elementos para esta fecha.", "Aucun élément à cette date.", "Keine Kalendereinträge für dieses Datum.", "この日の予定はありません。", "이 날짜에는 일정이 없습니다.", "Não há itens para esta data."),
  "Local-first · Your data stays on this device": copy("Local-first · Your data stays on this device", "本地优先 · 数据始终保留在此设备上", "Local primero · Tus datos permanecen en este dispositivo", "Local d’abord · Vos données restent sur cet appareil", "Lokal zuerst · Deine Daten bleiben auf diesem Gerät", "ローカル優先 · データはこの端末内に保存", "로컬 우선 · 데이터는 이 기기에만 저장", "Local primeiro · Os dados ficam neste dispositivo"),
  Tasks: copy("Tasks", "任务", "Tareas", "Tâches", "Aufgaben", "タスク", "작업", "Tarefas"),
  "No open tasks": copy("No open tasks", "没有待办任务", "No hay tareas abiertas", "Aucune tâche ouverte", "Keine offenen Aufgaben", "未完了のタスクはありません", "진행 중인 작업 없음", "Sem tarefas em aberto"),
  "Tasks generated from Structured Notes will appear here.": copy("Tasks generated from Structured Notes will appear here.", "从结构化笔记生成的任务会显示在这里。", "Las tareas de notas estructuradas aparecerán aquí.", "Les tâches issues des notes structurées apparaîtront ici.", "Aufgaben aus strukturierten Notizen erscheinen hier.", "構造化ノートから生成されたタスクがここに表示されます。", "구조화된 노트에서 생성된 작업이 여기에 표시됩니다.", "As tarefas de notas estruturadas aparecem aqui."),
  "Tasks and calendar follow-ups from your notes will appear here.": copy("Tasks and calendar follow-ups from your notes will appear here.", "笔记中的任务和日历跟进事项会显示在这里。", "Aquí aparecerán las tareas y seguimientos del calendario de tus notas.", "Les tâches et suivis du calendrier de vos notes apparaîtront ici.", "Aufgaben und Kalendertermine aus deinen Notizen erscheinen hier.", "ノートのタスクとカレンダーのフォローアップがここに表示されます。", "노트의 작업과 캘린더 후속 항목이 여기에 표시됩니다.", "As tarefas e acompanhamentos do calendário das suas notas aparecem aqui."),
  "Calendar follow-ups": copy("Calendar follow-ups", "日历跟进事项", "Seguimientos del calendario", "Suivis du calendrier", "Kalendertermine", "カレンダーのフォローアップ", "캘린더 후속 항목", "Acompanhamentos do calendário"),
  "Ask AI": copy("Ask AI", "询问 AI", "Preguntar a la IA", "Demander à l’IA", "KI fragen", "AIに質問", "AI에게 질문", "Perguntar à IA"),
  "Open Ask AI": copy("Open Ask AI", "打开询问 AI", "Abrir Preguntar a la IA", "Ouvrir Demander à l’IA", "KI fragen öffnen", "AIに質問を開く", "AI에게 질문 열기", "Abrir Perguntar à IA"),
  Ask: copy("Ask", "询问", "Preguntar", "Demander", "Fragen", "質問", "질문", "Perguntar"),
  "LOCAL TRANSCRIPT AI": copy("LOCAL TRANSCRIPT AI", "本地转写 AI", "IA LOCAL DE TRANSCRIPCIÓN", "IA LOCALE DE TRANSCRIPTION", "LOKALE TRANSKRIPT-KI", "ローカル文字起こしAI", "로컬 전사 AI", "IA LOCAL DE TRANSCRIÇÃO"),
  "Ask about up to three transcripts. Answers use only the selected note content.": copy("Ask about up to three transcripts. Answers use only the selected note content.", "可针对最多三篇转写提问，回答仅使用所选笔记的内容。", "Pregunta sobre hasta tres transcripciones. Las respuestas solo usan el contenido seleccionado.", "Posez des questions sur trois transcriptions au maximum. Les réponses utilisent uniquement le contenu sélectionné.", "Frage zu bis zu drei Transkripten. Antworten verwenden nur die ausgewählten Inhalte.", "最大3件の文字起こしについて質問できます。回答には選択したノートの内容のみを使用します。", "최대 3개의 전사에 관해 질문하세요. 답변은 선택한 노트 내용만 사용합니다.", "Pergunte sobre até três transcrições. As respostas usam apenas o conteúdo selecionado."),
  History: copy("History", "历史记录", "Historial", "Historique", "Verlauf", "履歴", "기록", "Histórico"),
  "You don't have any transcripts yet.": copy("You don't have any transcripts yet.", "你还没有任何转写。", "Todavía no tienes transcripciones.", "Vous n’avez pas encore de transcription.", "Du hast noch keine Transkripte.", "文字起こしはまだありません。", "아직 전사 내용이 없습니다.", "Ainda não tem transcrições."),
  "Untitled transcript": copy("Untitled transcript", "未命名转写", "Transcripción sin título", "Transcription sans titre", "Unbenanntes Transkript", "無題の文字起こし", "제목 없는 전사", "Transcrição sem título"),
  "Based on": copy("Based on", "依据", "Basado en", "Basé sur", "Basiert auf", "参照元", "기준", "Com base em"),
  "Context locked for this conversation": copy("Context locked for this conversation", "此对话的上下文已锁定", "Contexto bloqueado para esta conversación", "Contexte verrouillé pour cette conversation", "Kontext für diese Unterhaltung gesperrt", "この会話のコンテキストは固定されています", "이 대화의 컨텍스트가 고정되었습니다", "Contexto bloqueado para esta conversa"),
  Change: copy("Change", "更改", "Cambiar", "Modifier", "Ändern", "変更", "변경", "Alterar"),
  New: copy("New", "新建", "Nuevo", "Nouveau", "Neu", "新規", "새로 만들기", "Novo"),
  "Open models": copy("Open models", "打开模型", "Abrir modelos", "Ouvrir les modèles", "Modelle öffnen", "モデルを開く", "모델 열기", "Abrir modelos"),
  "New conversation": copy("New conversation", "新建对话", "Nueva conversación", "Nouvelle conversation", "Neue Unterhaltung", "新しい会話", "새 대화", "Nova conversa"),
  Retry: copy("Retry", "重试", "Reintentar", "Réessayer", "Erneut versuchen", "再試行", "다시 시도", "Tentar novamente"),
  "AI answer": copy("AI answer", "AI 回答", "Respuesta de la IA", "Réponse de l’IA", "KI-Antwort", "AIの回答", "AI 답변", "Resposta da IA"),
  "AI is working": copy("AI is working", "AI 正在处理", "La IA está trabajando", "L’IA travaille", "KI arbeitet", "AIが処理中", "AI가 작업 중", "A IA está a trabalhar"),
  "AI is working…": copy("AI is working…", "AI 正在处理……", "La IA está trabajando…", "L’IA travaille…", "KI arbeitet …", "AIが処理中…", "AI가 작업 중…", "A IA está a trabalhar…"),
  "Starting microphone": copy("Starting microphone", "正在启动麦克风", "Iniciando micrófono", "Démarrage du microphone", "Mikrofon wird gestartet", "マイクを起動中", "마이크 시작 중", "A iniciar o microfone"),
  "Finishing transcription": copy("Finishing transcription", "正在完成转写", "Finalizando transcripción", "Finalisation de la transcription", "Transkription wird abgeschlossen", "文字起こしを完了中", "전사 완료 중", "A concluir a transcrição"),
  "Recording question": copy("Recording question", "正在录制问题", "Grabando pregunta", "Enregistrement de la question", "Frage wird aufgenommen", "質問を録音中", "질문 녹음 중", "A gravar a pergunta"),
  "Your spoken question will appear here.": copy("Your spoken question will appear here.", "你说出的问题会显示在这里。", "Tu pregunta hablada aparecerá aquí.", "Votre question orale apparaîtra ici.", "Deine gesprochene Frage erscheint hier.", "話した質問がここに表示されます。", "말한 질문이 여기에 표시됩니다.", "A sua pergunta falada aparecerá aqui."),
  "Ask about the selected transcripts...": copy("Ask about the selected transcripts...", "针对所选转写提问……", "Pregunta sobre las transcripciones seleccionadas...", "Posez une question sur les transcriptions sélectionnées…", "Frage zu den ausgewählten Transkripten …", "選択した文字起こしについて質問…", "선택한 전사에 관해 질문하세요...", "Pergunte sobre as transcrições selecionadas..."),
  Mic: copy("Mic", "麦克风", "Micrófono", "Micro", "Mikrofon", "マイク", "마이크", "Microfone"),
  "Sending...": copy("Sending...", "正在发送……", "Enviando...", "Envoi…", "Wird gesendet …", "送信中…", "전송 중...", "A enviar..."),
  Send: copy("Send", "发送", "Enviar", "Envoyer", "Senden", "送信", "보내기", "Enviar"),
  "Choose up to 3 transcripts": copy("Choose up to 3 transcripts", "选择最多 3 篇转写", "Elige hasta 3 transcripciones", "Choisissez jusqu’à 3 transcriptions", "Bis zu 3 Transkripte auswählen", "最大3件の文字起こしを選択", "최대 3개의 전사 선택", "Escolha até 3 transcrições"),
  "AI History": copy("AI History", "AI 历史记录", "Historial de IA", "Historique de l’IA", "KI-Verlauf", "AI履歴", "AI 기록", "Histórico de IA"),
  "No Ask AI conversations yet.": copy("No Ask AI conversations yet.", "还没有询问 AI 对话。", "Aún no hay conversaciones con la IA.", "Aucune conversation avec l’IA pour le moment.", "Noch keine KI-Unterhaltungen.", "AIとの会話はまだありません。", "아직 AI 대화가 없습니다.", "Ainda não há conversas com a IA."),
  "Start with a question about the selected transcript.": copy("Start with a question about the selected transcript.", "先针对所选转写提出一个问题。", "Empieza con una pregunta sobre la transcripción seleccionada.", "Commencez par une question sur la transcription sélectionnée.", "Beginne mit einer Frage zum ausgewählten Transkript.", "選択した文字起こしについて質問してみましょう。", "선택한 전사에 관한 질문으로 시작하세요.", "Comece com uma pergunta sobre a transcrição selecionada."),
  "The last question has not received an assistant response yet.": copy("The last question has not received an assistant response yet.", "上一个问题尚未收到 AI 回答。", "La última pregunta aún no ha recibido respuesta.", "La dernière question n’a pas encore reçu de réponse.", "Die letzte Frage wurde noch nicht beantwortet.", "最後の質問にはまだ回答がありません。", "마지막 질문에 아직 답변이 없습니다.", "A última pergunta ainda não recebeu resposta."),
  "Restore all source notes and workspaces to continue this conversation. Saved messages remain readable.": copy("Restore all source notes and workspaces to continue this conversation. Saved messages remain readable.", "恢复所有来源笔记和工作区后才能继续此对话；已保存的消息仍可查看。", "Restaura todas las notas y espacios de origen para continuar. Los mensajes guardados siguen disponibles.", "Restaurez toutes les notes et tous les espaces sources pour continuer. Les messages enregistrés restent lisibles.", "Stelle alle Quellnotizen und Arbeitsbereiche wieder her. Gespeicherte Nachrichten bleiben lesbar.", "会話を続けるには参照元のノートとワークスペースをすべて復元してください。保存済みメッセージは閲覧できます。", "대화를 계속하려면 원본 노트와 작업 공간을 모두 복원하세요. 저장된 메시지는 계속 볼 수 있습니다.", "Restaure todas as notas e espaços de origem para continuar. As mensagens guardadas permanecem legíveis."),
  "Finish the current turn first. Retry the last question or start a new conversation.": copy("Finish the current turn first. Retry the last question or start a new conversation.", "请先完成当前轮次，重试上一个问题或新建对话。", "Termina primero el turno actual. Reintenta la última pregunta o inicia otra conversación.", "Terminez d’abord l’échange actuel. Réessayez la dernière question ou démarrez une nouvelle conversation.", "Schließe zuerst die aktuelle Runde ab. Wiederhole die letzte Frage oder beginne eine neue Unterhaltung.", "現在のやり取りを先に完了してください。最後の質問を再試行するか、新しい会話を始めてください。", "현재 대화를 먼저 완료하세요. 마지막 질문을 다시 시도하거나 새 대화를 시작하세요.", "Conclua primeiro o turno atual. Repita a última pergunta ou inicie uma nova conversa."),
  "Select at least one transcript before asking.": copy("Select at least one transcript before asking.", "提问前请至少选择一篇转写。", "Selecciona al menos una transcripción antes de preguntar.", "Sélectionnez au moins une transcription avant de poser une question.", "Wähle vor dem Fragen mindestens ein Transkript aus.", "質問する前に文字起こしを1件以上選択してください。", "질문하기 전에 전사를 하나 이상 선택하세요.", "Selecione pelo menos uma transcrição antes de perguntar."),
  "Restore all source notes and workspaces before asking another question.": copy("Restore all source notes and workspaces before asking another question.", "提出下一个问题前，请恢复所有来源笔记和工作区。", "Restaura todas las notas y espacios de origen antes de hacer otra pregunta.", "Restaurez toutes les notes et tous les espaces sources avant de poser une autre question.", "Stelle alle Quellnotizen und Arbeitsbereiche wieder her, bevor du weiterfragst.", "別の質問をする前に参照元のノートとワークスペースをすべて復元してください。", "다른 질문을 하기 전에 원본 노트와 작업 공간을 모두 복원하세요.", "Restaure todas as notas e espaços de origem antes de fazer outra pergunta."),
  "Generation stopped.": copy("Generation stopped.", "生成已停止。", "Generación detenida.", "Génération arrêtée.", "Generierung gestoppt.", "生成を停止しました。", "생성이 중지되었습니다.", "Geração interrompida."),
  "Microphone permission is required.": copy("Microphone permission is required.", "需要麦克风权限。", "Se requiere permiso para usar el micrófono.", "L’autorisation du microphone est requise.", "Mikrofonberechtigung ist erforderlich.", "マイクの権限が必要です。", "마이크 권한이 필요합니다.", "É necessária permissão para o microfone."),
  "Transcription did not produce a question.": copy("Transcription did not produce a question.", "转写未生成可提问的内容。", "La transcripción no produjo una pregunta.", "La transcription n’a produit aucune question.", "Die Transkription ergab keine Frage.", "文字起こしから質問を取得できませんでした。", "전사에서 질문을 만들지 못했습니다.", "A transcrição não produziu uma pergunta."),
  "Something went wrong.": copy("Something went wrong.", "出现错误。", "Algo salió mal.", "Une erreur s’est produite.", "Etwas ist schiefgelaufen.", "問題が発生しました。", "문제가 발생했습니다.", "Algo correu mal."),
  "Select up to 3 notes.": copy("Select up to 3 notes.", "最多选择 3 篇笔记。", "Selecciona hasta 3 notas.", "Sélectionnez jusqu’à 3 notes.", "Wähle bis zu 3 Notizen aus.", "ノートは最大3件まで選択できます。", "노트를 최대 3개 선택하세요.", "Selecione até 3 notas."),
  "One or more selected notes are unavailable.": copy("One or more selected notes are unavailable.", "一篇或多篇所选笔记不可用。", "Una o más notas seleccionadas no están disponibles.", "Une ou plusieurs notes sélectionnées sont indisponibles.", "Eine oder mehrere ausgewählte Notizen sind nicht verfügbar.", "選択したノートの一部を利用できません。", "선택한 노트 중 하나 이상을 사용할 수 없습니다.", "Uma ou mais notas selecionadas não estão disponíveis."),
  "The active model file is missing on this device.": copy("The active model file is missing on this device.", "此设备上缺少当前启用的模型文件。", "Falta el archivo del modelo activo en este dispositivo.", "Le fichier du modèle actif est absent de cet appareil.", "Die Datei des aktiven Modells fehlt auf diesem Gerät.", "この端末に有効なモデルファイルがありません。", "이 기기에 활성 모델 파일이 없습니다.", "O ficheiro do modelo ativo não existe neste dispositivo."),
  "No active language model. Download and activate a model first.": copy("No active language model. Download and activate a model first.", "没有启用的语言模型，请先下载并启用一个模型。", "No hay un modelo de lenguaje activo. Descarga y activa uno primero.", "Aucun modèle de langage actif. Téléchargez et activez d’abord un modèle.", "Kein aktives Sprachmodell. Lade zuerst ein Modell herunter und aktiviere es.", "有効な言語モデルがありません。先にモデルをダウンロードして有効にしてください。", "활성 언어 모델이 없습니다. 먼저 모델을 다운로드하고 활성화하세요.", "Não existe um modelo de linguagem ativo. Transfira e ative primeiro um modelo."),
  "This transcript is too long for the current context window. Choose a shorter transcript or use a model/configuration with a larger supported context.": copy("This transcript is too long for the current context window. Choose a shorter transcript or use a model/configuration with a larger supported context.", "此转写内容超出当前上下文窗口，请选择较短的转写或使用支持更大上下文的模型配置。", "Esta transcripción es demasiado larga para el contexto actual. Elige una más corta o un modelo con mayor contexto.", "Cette transcription est trop longue pour la fenêtre de contexte actuelle. Choisissez-en une plus courte ou un modèle prenant en charge un contexte plus large.", "Dieses Transkript ist für das aktuelle Kontextfenster zu lang. Wähle ein kürzeres oder ein Modell mit größerem Kontext.", "この文字起こしは現在のコンテキスト上限を超えています。短い文字起こし、またはより大きなコンテキスト対応モデルを選択してください。", "이 전사는 현재 컨텍스트 창에 비해 너무 깁니다. 더 짧은 전사나 더 큰 컨텍스트를 지원하는 모델을 사용하세요.", "Esta transcrição é demasiado longa para a janela de contexto atual. Escolha uma mais curta ou um modelo com contexto maior."),
  Manage: copy("Manage", "管理", "Gestionar", "Gérer", "Verwalten", "管理", "관리", "Gerir"),
  "Speech-to-Text Models": copy("Speech-to-Text Models", "语音转文字模型", "Modelos de voz a texto", "Modèles parole-texte", "Speech-to-Text-Modelle", "音声認識モデル", "음성-텍스트 모델", "Modelos de voz para texto"),
  "Large Language Models": copy("Large Language Models", "大语言模型", "Modelos de lenguaje", "Grands modèles de langage", "Große Sprachmodelle", "大規模言語モデル", "대규모 언어 모델", "Grandes modelos de linguagem"),
  "Text-to-Speech Models": copy("Text-to-Speech Models", "文字转语音模型", "Modelos de texto a voz", "Modèles texte-parole", "Text-to-Speech-Modelle", "音声合成モデル", "텍스트-음성 모델", "Modelos de texto para voz"),
  "Knowledge Templates": copy("Knowledge Templates", "知识模板", "Plantillas de conocimiento", "Modèles de connaissances", "Wissensvorlagen", "ナレッジテンプレート", "지식 템플릿", "Modelos de conhecimento"),
  "Manage Knowledge templates": copy("Manage Knowledge templates", "管理知识模板", "Gestionar plantillas de conocimiento", "Gérer les modèles de connaissances", "Wissensvorlagen verwalten", "ナレッジテンプレートを管理", "지식 템플릿 관리", "Gerir modelos de conhecimento"),
  "Create reusable extraction structures with local AI.": copy("Create reusable extraction structures with local AI.", "使用本地 AI 创建可复用的信息提取结构。", "Crea estructuras de extracción reutilizables con IA local.", "Créez des structures d’extraction réutilisables avec l’IA locale.", "Wiederverwendbare Extraktionsstrukturen mit lokaler KI erstellen.", "ローカルAIで再利用可能な抽出構造を作成します。", "로컬 AI로 재사용 가능한 추출 구조를 만드세요.", "Crie estruturas de extração reutilizáveis com IA local."),
  "Custom templates": copy("Custom templates", "自定义模板", "Plantillas personalizadas", "Modèles personnalisés", "Benutzerdefinierte Vorlagen", "カスタムテンプレート", "사용자 지정 템플릿", "Modelos personalizados"),
  "Built-in templates remain read-only. Custom templates define future Knowledge generations.": copy("Built-in templates remain read-only. Custom templates define future Knowledge generations.", "内置模板保持只读。自定义模板将用于之后生成知识内容。", "Las plantillas integradas son de solo lectura. Las personalizadas definen futuras generaciones de conocimiento.", "Les modèles intégrés restent en lecture seule. Les modèles personnalisés définissent les prochaines générations de connaissances.", "Integrierte Vorlagen bleiben schreibgeschützt. Benutzerdefinierte Vorlagen bestimmen künftige Wissensgenerierungen.", "組み込みテンプレートは読み取り専用です。カスタムテンプレートは今後のナレッジ生成に使用されます。", "기본 제공 템플릿은 읽기 전용입니다. 사용자 지정 템플릿은 이후 지식 생성에 사용됩니다.", "Os modelos integrados permanecem só de leitura. Os personalizados definem futuras gerações de conhecimento."),
  "＋ New": copy("＋ New", "＋ 新建", "＋ Nueva", "＋ Nouveau", "＋ Neu", "＋ 新規", "＋ 새로 만들기", "＋ Novo"),
  "No custom templates": copy("No custom templates", "暂无自定义模板", "No hay plantillas personalizadas", "Aucun modèle personnalisé", "Keine benutzerdefinierten Vorlagen", "カスタムテンプレートはありません", "사용자 지정 템플릿 없음", "Sem modelos personalizados"),
  "Describe what you want to extract and local AI will propose the sections.": copy("Describe what you want to extract and local AI will propose the sections.", "描述你想提取的内容，本地 AI 将为你建议各个部分。", "Describe qué quieres extraer y la IA local propondrá las secciones.", "Décrivez ce que vous souhaitez extraire et l’IA locale proposera les sections.", "Beschreibe, was extrahiert werden soll, und die lokale KI schlägt Abschnitte vor.", "抽出したい内容を説明すると、ローカルAIがセクションを提案します。", "추출할 내용을 설명하면 로컬 AI가 섹션을 제안합니다.", "Descreva o que pretende extrair e a IA local irá propor as secções."),
  Edit: copy("Edit", "编辑", "Editar", "Modifier", "Bearbeiten", "編集", "편집", "Editar"),
  Trash: copy("Trash", "移到废纸篓", "Papelera", "Corbeille", "Papierkorb", "ゴミ箱", "휴지통", "Lixo"),
  "Edit template": copy("Edit template", "编辑模板", "Editar plantilla", "Modifier le modèle", "Vorlage bearbeiten", "テンプレートを編集", "템플릿 편집", "Editar modelo"),
  "New template": copy("New template", "新建模板", "Nueva plantilla", "Nouveau modèle", "Neue Vorlage", "新規テンプレート", "새 템플릿", "Novo modelo"),
  "Edits affect future generations only. Saved results keep their original structure.": copy("Edits affect future generations only. Saved results keep their original structure.", "编辑仅影响之后生成的内容，已保存结果会保留原有结构。", "Los cambios solo afectan a futuras generaciones. Los resultados guardados conservan su estructura original.", "Les modifications concernent uniquement les prochaines générations. Les résultats enregistrés conservent leur structure.", "Änderungen wirken sich nur auf künftige Generierungen aus. Gespeicherte Ergebnisse behalten ihre Struktur.", "編集は今後の生成にのみ反映されます。保存済みの結果は元の構造を維持します。", "편집 내용은 이후 생성에만 적용됩니다. 저장된 결과는 기존 구조를 유지합니다.", "As edições afetam apenas futuras gerações. Os resultados guardados mantêm a estrutura original."),
  "e.g. Research Review": copy("e.g. Research Review", "例如：研究综述", "p. ej., Revisión de investigación", "ex. Revue de recherche", "z. B. Forschungsüberblick", "例：研究レビュー", "예: 연구 검토", "ex.: Revisão de investigação"),
  "What should this template extract?": copy("What should this template extract?", "这个模板应提取什么？", "¿Qué debe extraer esta plantilla?", "Que doit extraire ce modèle ?", "Was soll diese Vorlage extrahieren?", "このテンプレートで何を抽出しますか？", "이 템플릿에서 무엇을 추출할까요?", "O que deve este modelo extrair?"),
  "Describe the information and organization you need…": copy("Describe the information and organization you need…", "描述你需要的信息和组织方式……", "Describe la información y organización que necesitas…", "Décrivez les informations et l’organisation souhaitées…", "Beschreibe die benötigten Informationen und ihre Gliederung …", "必要な情報と構成を説明してください…", "필요한 정보와 구성 방식을 설명하세요…", "Descreva as informações e a organização de que necessita…"),
  "Cancel Proposal": copy("Cancel Proposal", "取消建议", "Cancelar propuesta", "Annuler la proposition", "Vorschlag abbrechen", "提案をキャンセル", "제안 취소", "Cancelar proposta"),
  "Retry Proposal": copy("Retry Proposal", "重试建议", "Reintentar propuesta", "Réessayer la proposition", "Vorschlag erneut versuchen", "提案を再試行", "제안 다시 시도", "Repetir proposta"),
  "Propose Sections": copy("Propose Sections", "建议分区", "Proponer secciones", "Proposer des sections", "Abschnitte vorschlagen", "セクションを提案", "섹션 제안", "Propor secções"),
  "Build Manually": copy("Build Manually", "手动创建", "Crear manualmente", "Créer manuellement", "Manuell erstellen", "手動で作成", "직접 만들기", "Criar manualmente"),
  "＋ Add": copy("＋ Add", "＋ 添加", "＋ Añadir", "＋ Ajouter", "＋ Hinzufügen", "＋ 追加", "＋ 추가", "＋ Adicionar"),
  Remove: copy("Remove", "移除", "Eliminar", "Retirer", "Entfernen", "削除", "제거", "Remover"),
  Title: copy("Title", "标题", "Título", "Titre", "Titel", "タイトル", "제목", "Título"),
  "Section title": copy("Section title", "分区标题", "Título de la sección", "Titre de la section", "Abschnittstitel", "セクションタイトル", "섹션 제목", "Título da secção"),
  "Extraction guidance": copy("Extraction guidance", "提取说明", "Guía de extracción", "Consignes d’extraction", "Extraktionsanleitung", "抽出ガイド", "추출 지침", "Orientações de extração"),
  "What grounded information belongs here?": copy("What grounded information belongs here?", "这里应包含哪些有依据的信息？", "¿Qué información fundamentada corresponde aquí?", "Quelles informations étayées doivent figurer ici ?", "Welche belegten Informationen gehören hierher?", "ここにはどのような根拠のある情報を含めますか？", "여기에 어떤 근거 있는 정보가 포함되어야 하나요?", "Que informações fundamentadas pertencem aqui?"),
  "Saving…": copy("Saving…", "正在保存……", "Guardando…", "Enregistrement…", "Wird gespeichert …", "保存中…", "저장 중…", "A guardar…"),
  "Save Template": copy("Save Template", "保存模板", "Guardar plantilla", "Enregistrer le modèle", "Vorlage speichern", "テンプレートを保存", "템플릿 저장", "Guardar modelo"),
  "Propose Again": copy("Propose Again", "重新建议", "Proponer de nuevo", "Proposer à nouveau", "Erneut vorschlagen", "再提案", "다시 제안", "Propor novamente"),
  "Unable to load templates.": copy("Unable to load templates.", "无法加载模板。", "No se pudieron cargar las plantillas.", "Impossible de charger les modèles.", "Vorlagen konnten nicht geladen werden.", "テンプレートを読み込めませんでした。", "템플릿을 불러올 수 없습니다.", "Não foi possível carregar os modelos."),
  "Unable to propose sections.": copy("Unable to propose sections.", "无法建议分区。", "No se pudieron proponer las secciones.", "Impossible de proposer des sections.", "Abschnitte konnten nicht vorgeschlagen werden.", "セクションを提案できませんでした。", "섹션을 제안할 수 없습니다.", "Não foi possível propor secções."),
  "Unable to save template.": copy("Unable to save template.", "无法保存模板。", "No se pudo guardar la plantilla.", "Impossible d’enregistrer le modèle.", "Vorlage konnte nicht gespeichert werden.", "テンプレートを保存できませんでした。", "템플릿을 저장할 수 없습니다.", "Não foi possível guardar o modelo."),
  "Move template to Trash?": copy("Move template to Trash?", "将模板移到废纸篓？", "¿Mover la plantilla a la papelera?", "Déplacer le modèle vers la corbeille ?", "Vorlage in den Papierkorb verschieben?", "テンプレートをゴミ箱に移動しますか？", "템플릿을 휴지통으로 이동할까요?", "Mover o modelo para o lixo?"),
  "Existing Knowledge results remain unchanged and readable.": copy("Existing Knowledge results remain unchanged and readable.", "现有知识结果将保持不变且仍可查看。", "Los resultados de conocimiento existentes no cambiarán y seguirán disponibles.", "Les résultats de connaissances existants restent inchangés et lisibles.", "Vorhandene Wissensergebnisse bleiben unverändert und lesbar.", "既存のナレッジ結果は変更されず、引き続き閲覧できます。", "기존 지식 결과는 변경되지 않으며 계속 볼 수 있습니다.", "Os resultados de conhecimento existentes permanecem inalterados e legíveis."),
  "Move to Trash": copy("Move to Trash", "移到废纸篓", "Mover a la papelera", "Déplacer vers la corbeille", "In den Papierkorb", "ゴミ箱に移動", "휴지통으로 이동", "Mover para o lixo"),
  "Unable to move template": copy("Unable to move template", "无法移动模板", "No se pudo mover la plantilla", "Impossible de déplacer le modèle", "Vorlage konnte nicht verschoben werden", "テンプレートを移動できませんでした", "템플릿을 이동할 수 없습니다", "Não foi possível mover o modelo"),
  Active: copy("Active", "已启用", "Activo", "Actif", "Aktiv", "有効", "활성", "Ativo"),
  Downloading: copy("Downloading", "正在下载", "Descargando", "Téléchargement", "Wird heruntergeladen", "ダウンロード中", "다운로드 중", "A transferir"),
  "In use — switch models before uninstalling this one.": copy("In use — switch models before uninstalling this one.", "正在使用中，请先切换模型再卸载。", "En uso: cambia de modelo antes de desinstalarlo.", "En cours d’utilisation — changez de modèle avant de le désinstaller.", "In Verwendung — vor der Deinstallation Modell wechseln.", "使用中です。アンインストール前にモデルを切り替えてください。", "사용 중 — 제거하기 전에 모델을 전환하세요.", "Em uso — mude de modelo antes de desinstalar."),
  "Currently used for local speech synthesis.": copy("Currently used for local speech synthesis.", "当前用于本地语音合成。", "Se usa para síntesis de voz local.", "Utilisé pour la synthèse vocale locale.", "Wird für lokale Sprachsynthese verwendet.", "ローカル音声合成に使用中です。", "현재 로컬 음성 합성에 사용 중입니다.", "Usado atualmente para síntese de voz local."),
  "Audio and transcription stay on this device.": copy("Audio and transcription stay on this device.", "音频和转写内容仅保留在此设备上。", "El audio y la transcripción permanecen en este dispositivo.", "L’audio et la transcription restent sur cet appareil.", "Audio und Transkription bleiben auf diesem Gerät.", "音声と文字起こしはこの端末内に保存されます。", "오디오와 전사 내용은 이 기기에만 저장됩니다.", "O áudio e a transcrição ficam neste dispositivo."),
  "Start recording": copy("Start recording", "开始录音", "Iniciar grabación", "Démarrer l’enregistrement", "Aufnahme starten", "録音を開始", "녹음 시작", "Iniciar gravação"),
  "Tap the button to begin live transcription": copy("Tap the button to begin live transcription", "点击按钮开始实时转写", "Pulsa el botón para iniciar la transcripción", "Touchez le bouton pour lancer la transcription", "Tippe auf die Schaltfläche, um zu starten", "ボタンをタップして文字起こしを開始", "버튼을 눌러 실시간 전사를 시작하세요", "Toque no botão para iniciar a transcrição"),
  Finish: copy("Finish", "完成", "Finalizar", "Terminer", "Beenden", "完了", "완료", "Terminar"),
  "Save transcription": copy("Save transcription", "保存转写", "Guardar transcripción", "Enregistrer la transcription", "Transkription speichern", "文字起こしを保存", "전사 저장", "Guardar transcrição"),
  Discard: copy("Discard", "丢弃", "Descartar", "Supprimer", "Verwerfen", "破棄", "버리기", "Descartar"),
  "Note name": copy("Note name", "笔记名称", "Nombre de la nota", "Nom de la note", "Notizname", "ノート名", "노트 이름", "Nome da nota"),
  Workspace: copy("Workspace", "工作区", "Espacio", "Espace", "Arbeitsbereich", "ワークスペース", "작업 공간", "Espaço"),
  "Choose an audio file": copy("Choose an audio file", "选择音频文件", "Elegir un archivo de audio", "Choisir un fichier audio", "Audiodatei auswählen", "音声ファイルを選択", "오디오 파일 선택", "Escolher um ficheiro de áudio"),
  "Recording audio": copy("Recording audio", "录音音频", "Audio grabado", "Audio enregistré", "Audioaufnahme", "録音音声", "녹음 오디오", "Áudio gravado"),
  Play: copy("Play", "播放", "Reproducir", "Lire", "Abspielen", "再生", "재생", "Reproduzir"),
  Pause: copy("Pause", "暂停", "Pausa", "Pause", "Pause", "一時停止", "일시 정지", "Pausa"),
  "Tap to listen": copy("Tap to listen", "点击收听", "Pulsa para escuchar", "Touchez pour écouter", "Zum Anhören tippen", "タップして再生", "탭하여 듣기", "Toque para ouvir"),
  "Playing on this device": copy("Playing on this device", "正在此设备上播放", "Reproduciendo en este dispositivo", "Lecture sur cet appareil", "Wiedergabe auf diesem Gerät", "この端末で再生中", "이 기기에서 재생 중", "A reproduzir neste dispositivo"),
  "Structured Note": copy("Structured Note", "结构化笔记", "Nota estructurada", "Note structurée", "Strukturierte Notiz", "構造化ノート", "구조화된 노트", "Nota estruturada"),
  Summary: copy("Summary", "摘要", "Resumen", "Résumé", "Zusammenfassung", "要約", "요약", "Resumo"),
  "Key Points": copy("Key Points", "要点", "Puntos clave", "Points clés", "Kernpunkte", "要点", "핵심 사항", "Pontos-chave"),
  Reminders: copy("Reminders", "提醒", "Recordatorios", "Rappels", "Erinnerungen", "リマインダー", "알림", "Lembretes"),
  "Calendar Intents": copy("Calendar Intents", "日历事项", "Intenciones de calendario", "Intentions de calendrier", "Kalenderabsichten", "カレンダー予定", "캘린더 일정", "Intenções de calendário"),
  Close: copy("Close", "关闭", "Cerrar", "Fermer", "Schließen", "閉じる", "닫기", "Fechar"),
  "No other workspace is available.": copy("No other workspace is available.", "没有其他可用的工作区。", "No hay otro espacio disponible.", "Aucun autre espace n’est disponible.", "Kein anderer Arbeitsbereich verfügbar.", "他に利用できるワークスペースはありません。", "사용 가능한 다른 작업 공간이 없습니다.", "Não há outro espaço disponível."),
  "No actionable steps generated.": copy("No actionable steps generated.", "未生成可执行步骤。", "No se generaron pasos accionables.", "Aucune étape exploitable générée.", "Keine umsetzbaren Schritte erzeugt.", "実行可能な手順は生成されませんでした。", "실행 가능한 단계가 생성되지 않았습니다.", "Não foram gerados passos acionáveis."),
  "Unable to copy. Please try again.": copy("Unable to copy. Please try again.", "无法复制，请重试。", "No se pudo copiar. Inténtalo de nuevo.", "Impossible de copier. Réessayez.", "Kopieren nicht möglich. Bitte erneut versuchen.", "コピーできませんでした。もう一度お試しください。", "복사할 수 없습니다. 다시 시도하세요.", "Não foi possível copiar. Tente novamente."),
  Cancel: copy("Cancel", "取消", "Cancelar", "Annuler", "Abbrechen", "キャンセル", "취소", "Cancelar"),
  Delete: copy("Delete", "删除", "Eliminar", "Supprimer", "Löschen", "削除", "삭제", "Eliminar"),
  Save: copy("Save", "保存", "Guardar", "Enregistrer", "Speichern", "保存", "저장", "Guardar"),
  Create: copy("Create", "创建", "Crear", "Créer", "Erstellen", "作成", "만들기", "Criar"),
  Rename: copy("Rename", "重命名", "Cambiar nombre", "Renommer", "Umbenennen", "名前を変更", "이름 변경", "Mudar nome"),
  Move: copy("Move", "移动", "Mover", "Déplacer", "Verschieben", "移動", "이동", "Mover"),
  Uninstall: copy("Uninstall", "卸载", "Desinstalar", "Désinstaller", "Deinstallieren", "アンインストール", "제거", "Desinstalar"),
  "Uninstall model": copy("Uninstall model", "卸载模型", "Desinstalar modelo", "Désinstaller le modèle", "Modell deinstallieren", "モデルをアンインストール", "모델 제거", "Desinstalar modelo"),
  "Delete note?": copy("Delete note?", "删除笔记？", "¿Eliminar la nota?", "Supprimer la note ?", "Notiz löschen?", "ノートを削除しますか？", "노트를 삭제할까요?", "Eliminar nota?"),
  "Delete workspace?": copy("Delete workspace?", "删除工作区？", "¿Eliminar el espacio?", "Supprimer l’espace ?", "Arbeitsbereich löschen?", "ワークスペースを削除しますか？", "작업 공간을 삭제할까요?", "Eliminar espaço?"),
  "Unable to delete note": copy("Unable to delete note", "无法删除笔记", "No se pudo eliminar la nota", "Impossible de supprimer la note", "Notiz konnte nicht gelöscht werden", "ノートを削除できませんでした", "노트를 삭제할 수 없습니다", "Não foi possível eliminar a nota"),
  "Unable to delete workspace": copy("Unable to delete workspace", "无法删除工作区", "No se pudo eliminar el espacio", "Impossible de supprimer l’espace", "Arbeitsbereich konnte nicht gelöscht werden", "ワークスペースを削除できませんでした", "작업 공간을 삭제할 수 없습니다", "Não foi possível eliminar o espaço"),
  "Please try again.": copy("Please try again.", "请重试。", "Inténtalo de nuevo.", "Veuillez réessayer.", "Bitte erneut versuchen.", "もう一度お試しください。", "다시 시도하세요.", "Tente novamente."),
  "Finish transcription?": copy("Finish transcription?", "完成转写？", "¿Finalizar la transcripción?", "Terminer la transcription ?", "Transkription beenden?", "文字起こしを終了しますか？", "전사를 완료할까요?", "Terminar a transcrição?"),
  "Two-hour limit reached": copy("Two-hour limit reached", "已达到两小时上限", "Se alcanzó el límite de dos horas", "Limite de deux heures atteinte", "Zwei-Stunden-Limit erreicht", "2時間の上限に達しました", "2시간 제한에 도달했습니다", "Limite de duas horas atingido"),
  "e.g. Personal": copy("e.g. Personal", "例如：个人", "p. ej., Personal", "ex. Personnel", "z. B. Persönlich", "例：個人", "예: 개인", "ex.: Pessoal"),
  "e.g. Weekly planning": copy("e.g. Weekly planning", "例如：每周计划", "p. ej., Planificación semanal", "ex. Planification hebdomadaire", "z. B. Wochenplanung", "例：週間計画", "예: 주간 계획", "ex.: Planeamento semanal"),
  "e.g. Interview recording": copy("e.g. Interview recording", "例如：访谈录音", "p. ej., Grabación de entrevista", "ex. Enregistrement d’entretien", "z. B. Interviewaufnahme", "例：インタビュー録音", "예: 인터뷰 녹음", "ex.: Gravação de entrevista"),
  "Workspace name": copy("Workspace name", "工作区名称", "Nombre del espacio", "Nom de l’espace", "Name des Arbeitsbereichs", "ワークスペース名", "작업 공간 이름", "Nome do espaço"),
  "Write the note transcript...": copy("Write the note transcript...", "输入笔记转写内容……", "Escribe la transcripción de la nota...", "Écrivez la transcription de la note…", "Notiztranskript eingeben …", "ノートの文字起こしを入力…", "노트 전사 내용을 입력하세요...", "Escreva a transcrição da nota..."),
  "Note title": copy("Note title", "笔记标题", "Título de la nota", "Titre de la note", "Notiztitel", "ノートのタイトル", "노트 제목", "Título da nota"),
  "Search titles and transcripts": copy("Search titles and transcripts", "搜索标题和转写内容", "Buscar títulos y transcripciones", "Rechercher dans les titres et transcriptions", "Titel und Transkripte durchsuchen", "タイトルと文字起こしを検索", "제목 및 전사 검색", "Pesquisar títulos e transcrições"),
  "Search your notes": copy("Search your notes", "搜索笔记", "Busca en tus notas", "Recherchez dans vos notes", "Notizen durchsuchen", "ノートを検索", "노트 검색", "Pesquise nas suas notas"),
  "No notes found": copy("No notes found", "未找到笔记", "No se encontraron notas", "Aucune note trouvée", "Keine Notizen gefunden", "ノートが見つかりません", "노트를 찾을 수 없습니다", "Não foram encontradas notas"),
  Transcript: copy("Transcript", "转写", "Transcripción", "Transcription", "Transkript", "文字起こし", "전사", "Transcrição"),
  Insights: copy("Insights", "洞察", "Ideas", "Analyses", "Erkenntnisse", "インサイト", "인사이트", "Informações"),
  Knowledge: copy("Knowledge", "知识", "Conocimiento", "Connaissances", "Wissen", "ナレッジ", "지식", "Conhecimento"),
  "Key points": copy("Key points", "要点", "Puntos clave", "Points clés", "Kernpunkte", "要点", "핵심 사항", "Pontos-chave"),
  "Tasks & Action Plan": copy("Tasks & Action Plan", "任务与行动计划", "Tareas y plan de acción", "Tâches et plan d’action", "Aufgaben und Aktionsplan", "タスクと行動計画", "작업 및 실행 계획", "Tarefas e plano de ação"),
  "Summary, key points, tasks, reminders, and calendar events.": copy("Summary, key points, tasks, reminders, and calendar events.", "摘要、要点、任务、提醒和日历事项。", "Resumen, puntos clave, tareas, recordatorios y eventos.", "Résumé, points clés, tâches, rappels et événements.", "Zusammenfassung, Kernpunkte, Aufgaben, Erinnerungen und Termine.", "要約、要点、タスク、リマインダー、予定。", "요약, 핵심 사항, 작업, 알림 및 일정.", "Resumo, pontos-chave, tarefas, lembretes e eventos."),
  "Running privately on this device.": copy("Running privately on this device.", "正在此设备上私密运行。", "Se ejecuta de forma privada en este dispositivo.", "Exécution privée sur cet appareil.", "Private Ausführung auf diesem Gerät.", "この端末内でプライベートに実行中。", "이 기기에서 비공개로 실행 중입니다.", "Em execução privada neste dispositivo."),
  Copied: copy("Copied", "已复制", "Copiado", "Copié", "Kopiert", "コピー済み", "복사됨", "Copiado"),
  "Copy insights": copy("Copy insights", "复制洞察", "Copiar ideas", "Copier les analyses", "Erkenntnisse kopieren", "インサイトをコピー", "인사이트 복사", "Copiar informações"),
  "No supported scenario-specific information was found in this note.": copy("No supported scenario-specific information was found in this note.", "此笔记中未找到支持的场景特定信息。", "No se encontró información específica compatible.", "Aucune information spécifique prise en charge n’a été trouvée.", "Keine unterstützten szenariospezifischen Informationen gefunden.", "対応するシナリオ固有の情報はありません。", "지원되는 시나리오별 정보를 찾지 못했습니다.", "Não foi encontrada informação específica suportada."),
  "Choose an audio file from anywhere on your device. It never leaves this device.": copy("Choose an audio file from anywhere on your device. It never leaves this device.", "从设备中选择音频文件，文件不会离开此设备。", "Elige un archivo de tu dispositivo. Nunca saldrá de él.", "Choisissez un fichier sur votre appareil. Il ne le quitte jamais.", "Audiodatei auf dem Gerät wählen. Sie verlässt es nie.", "端末内の音声ファイルを選択します。外部には送信されません。", "기기에서 오디오 파일을 선택하세요. 파일은 기기 밖으로 전송되지 않습니다.", "Escolha um ficheiro no dispositivo. Nunca sai dele."),
  "No notes yet": copy("No notes yet", "还没有笔记", "Aún no hay notas", "Aucune note", "Noch keine Notizen", "ノートはまだありません", "아직 노트가 없습니다", "Ainda não há notas"),
  "No matching notes": copy("No matching notes", "没有匹配的笔记", "No hay notas coincidentes", "Aucune note correspondante", "Keine passenden Notizen", "一致するノートはありません", "일치하는 노트가 없습니다", "Não há notas correspondentes"),
  "No workspaces yet": copy("No workspaces yet", "还没有工作区", "Aún no hay espacios", "Aucun espace", "Noch keine Arbeitsbereiche", "ワークスペースはまだありません", "아직 작업 공간이 없습니다", "Ainda não há espaços"),
  "Total notes": copy("Total notes", "笔记总数", "Notas totales", "Total des notes", "Notizen gesamt", "ノート総数", "전체 노트", "Total de notas"),
  Pinned: copy("Pinned", "已置顶", "Fijadas", "Épinglées", "Angeheftet", "ピン留め", "고정됨", "Fixadas"),
  Characters: copy("Characters", "字符数", "Caracteres", "Caractères", "Zeichen", "文字数", "문자 수", "Caracteres"),
  "Open tasks": copy("Open tasks", "待办任务", "Tareas abiertas", "Tâches ouvertes", "Offene Aufgaben", "未完了のタスク", "진행 중인 작업", "Tarefas em aberto"),
  "Show all notes": copy("Show all notes", "显示全部笔记", "Mostrar todas las notas", "Afficher toutes les notes", "Alle Notizen anzeigen", "すべてのノートを表示", "모든 노트 보기", "Mostrar todas as notas"),
  "Filter pinned notes": copy("Filter pinned notes", "筛选置顶笔记", "Filtrar notas fijadas", "Filtrer les notes épinglées", "Angeheftete Notizen filtern", "ピン留めノートを絞り込む", "고정된 노트 필터링", "Filtrar notas fixadas"),
  "Filter unfinished notes": copy("Filter unfinished notes", "筛选含未完成任务的笔记", "Filtrar notas sin terminar", "Filtrer les notes non terminées", "Unfertige Notizen filtern", "未完了のノートを絞り込む", "완료되지 않은 노트 필터링", "Filtrar notas por concluir"),
  Overdue: copy("Overdue", "已逾期", "Vencidas", "En retard", "Überfällig", "期限切れ", "기한 지남", "Em atraso"),
  Today: copy("Today", "今天", "Hoy", "Aujourd’hui", "Heute", "今日", "오늘", "Hoje"),
  Upcoming: copy("Upcoming", "即将开始", "Próximas", "À venir", "Anstehend", "今後", "예정", "Próximas"),
  Unscheduled: copy("Unscheduled", "未安排", "Sin programar", "Non planifiées", "Nicht geplant", "未設定", "일정 없음", "Sem data"),
  " open across your Structured Notes": copy(" open across your Structured Notes", " 个待办任务，来自结构化笔记", " abiertas en tus notas estructuradas", " ouvertes dans vos notes structurées", " offen in deinen strukturierten Notizen", "件の未完了タスク（構造化ノート全体）", "개의 진행 중인 작업(구조화된 노트 전체)", " em aberto nas suas notas estruturadas"),
  "+ New workspace": copy("+ New workspace", "+ 新建工作区", "+ Nuevo espacio", "+ Nouvel espace", "+ Neuer Arbeitsbereich", "+ 新しいワークスペース", "+ 새 작업 공간", "+ Novo espaço"),
  "New workspace": copy("New workspace", "新建工作区", "Nuevo espacio", "Nouvel espace", "Neuer Arbeitsbereich", "新しいワークスペース", "새 작업 공간", "Novo espaço"),
  "Create workspace": copy("Create workspace", "创建工作区", "Crear espacio", "Créer l’espace", "Arbeitsbereich erstellen", "ワークスペースを作成", "작업 공간 만들기", "Criar espaço"),
  "Creating...": copy("Creating...", "正在创建……", "Creando...", "Création…", "Wird erstellt …", "作成中…", "만드는 중...", "A criar..."),
  Name: copy("Name", "名称", "Nombre", "Nom", "Name", "名前", "이름", "Nome"),
  "Search notes": copy("Search notes", "搜索笔记", "Buscar notas", "Rechercher des notes", "Notizen suchen", "ノートを検索", "노트 검색", "Pesquisar notas"),
  "Unable to load workspaces.": copy("Unable to load workspaces.", "无法加载工作区。", "No se pudieron cargar los espacios.", "Impossible de charger les espaces.", "Arbeitsbereiche konnten nicht geladen werden.", "ワークスペースを読み込めませんでした。", "작업 공간을 불러올 수 없습니다.", "Não foi possível carregar os espaços."),
  "Unable to create workspace.": copy("Unable to create workspace.", "无法创建工作区。", "No se pudo crear el espacio.", "Impossible de créer l’espace.", "Arbeitsbereich konnte nicht erstellt werden.", "ワークスペースを作成できませんでした。", "작업 공간을 만들 수 없습니다.", "Não foi possível criar o espaço."),
  "+ New note": copy("+ New note", "+ 新建笔记", "+ Nueva nota", "+ Nouvelle note", "+ Neue Notiz", "+ 新しいノート", "+ 새 노트", "+ Nova nota"),
  "＋ New note": copy("＋ New note", "＋ 新建笔记", "＋ Nueva nota", "＋ Nouvelle note", "＋ Neue Notiz", "＋ 新しいノート", "＋ 새 노트", "＋ Nova nota"),
  "New note": copy("New note", "新建笔记", "Nueva nota", "Nouvelle note", "Neue Notiz", "新しいノート", "새 노트", "Nova nota"),
  "Create note": copy("Create note", "创建笔记", "Crear nota", "Créer la note", "Notiz erstellen", "ノートを作成", "노트 만들기", "Criar nota"),
  "Title (optional)": copy("Title (optional)", "标题（可选）", "Título (opcional)", "Titre (facultatif)", "Titel (optional)", "タイトル（任意）", "제목(선택 사항)", "Título (opcional)"),
  "e.g. Team meeting": copy("e.g. Team meeting", "例如：团队会议", "p. ej., Reunión de equipo", "ex. Réunion d’équipe", "z. B. Teambesprechung", "例：チーム会議", "예: 팀 회의", "ex.: Reunião de equipa"),
  "Saving...": copy("Saving...", "正在保存……", "Guardando...", "Enregistrement…", "Wird gespeichert …", "保存中…", "저장 중...", "A guardar..."),
  "Save name": copy("Save name", "保存名称", "Guardar nombre", "Enregistrer le nom", "Namen speichern", "名前を保存", "이름 저장", "Guardar nome"),
  "Rename workspace": copy("Rename workspace", "重命名工作区", "Cambiar nombre del espacio", "Renommer l’espace", "Arbeitsbereich umbenennen", "ワークスペース名を変更", "작업 공간 이름 변경", "Mudar nome do espaço"),
  Done: copy("Done", "完成", "Listo", "Terminé", "Fertig", "完了", "완료", "Concluído"),
  note: copy("note", "条笔记", "nota", "note", "Notiz", "件のノート", "개 노트", "nota"),
  notes: copy("notes", "条笔记", "notas", "notes", "Notizen", "件のノート", "개 노트", "notas"),
  "AI Management": copy("AI Management", "AI 管理", "Gestión de IA", "Gestion de l’IA", "KI-Verwaltung", "AI管理", "AI 관리", "Gestão de IA"),
  "Manage the speech and language models that run locally on this device.": copy("Manage the speech and language models that run locally on this device.", "管理在此设备上本地运行的语音和语言模型。", "Gestiona los modelos de voz y lenguaje que se ejecutan localmente.", "Gérez les modèles vocaux et linguistiques exécutés localement.", "Sprach- und Sprachmodelle verwalten, die lokal auf diesem Gerät laufen.", "この端末でローカル実行される音声・言語モデルを管理します。", "이 기기에서 로컬로 실행되는 음성 및 언어 모델을 관리합니다.", "Gira os modelos de voz e linguagem executados localmente neste dispositivo."),
  "Speech recognition models for local transcription.": copy("Speech recognition models for local transcription.", "用于本地转写的语音识别模型。", "Modelos de reconocimiento de voz para transcripción local.", "Modèles de reconnaissance vocale pour la transcription locale.", "Spracherkennungsmodelle für lokale Transkription.", "ローカル文字起こし用の音声認識モデル。", "로컬 전사용 음성 인식 모델입니다.", "Modelos de reconhecimento de voz para transcrição local."),
  "Language models for private, on-device AI features.": copy("Language models for private, on-device AI features.", "用于私密设备端 AI 功能的语言模型。", "Modelos de lenguaje para funciones de IA privadas en el dispositivo.", "Modèles de langage pour les fonctions d’IA privées sur l’appareil.", "Sprachmodelle für private KI-Funktionen auf dem Gerät.", "端末内で動作するプライベートAI機能用の言語モデル。", "기기 내 비공개 AI 기능을 위한 언어 모델입니다.", "Modelos de linguagem para funcionalidades de IA privadas no dispositivo."),
  "Local voices for private, on-device speech synthesis.": copy("Local voices for private, on-device speech synthesis.", "用于私密设备端语音合成的本地语音。", "Voces locales para síntesis privada en el dispositivo.", "Voix locales pour la synthèse vocale privée sur l’appareil.", "Lokale Stimmen für private Sprachsynthese auf dem Gerät.", "端末内でのプライベート音声合成用ローカル音声。", "기기 내 비공개 음성 합성을 위한 로컬 음성입니다.", "Vozes locais para síntese de voz privada no dispositivo."),
  "Manage speech-to-text models": copy("Manage speech-to-text models", "管理语音转文字模型", "Gestionar modelos de voz a texto", "Gérer les modèles parole-texte", "Speech-to-Text-Modelle verwalten", "音声認識モデルを管理", "음성-텍스트 모델 관리", "Gerir modelos de voz para texto"),
  "Manage large language models": copy("Manage large language models", "管理大语言模型", "Gestionar modelos de lenguaje", "Gérer les grands modèles de langage", "Große Sprachmodelle verwalten", "大規模言語モデルを管理", "대규모 언어 모델 관리", "Gerir grandes modelos de linguagem"),
  "Manage text-to-speech models": copy("Manage text-to-speech models", "管理文字转语音模型", "Gestionar modelos de texto a voz", "Gérer les modèles texte-parole", "Text-to-Speech-Modelle verwalten", "音声合成モデルを管理", "텍스트-음성 모델 관리", "Gerir modelos de texto para voz"),
  "Download models to run speech recognition fully on this device.": copy("Download models to run speech recognition fully on this device.", "下载模型，在此设备上完全本地运行语音识别。", "Descarga modelos para ejecutar el reconocimiento de voz en el dispositivo.", "Téléchargez des modèles pour exécuter la reconnaissance vocale sur l’appareil.", "Modelle für vollständig lokale Spracherkennung herunterladen.", "この端末内で音声認識を実行するモデルをダウンロードします。", "이 기기에서 음성 인식을 완전히 로컬로 실행할 모델을 다운로드하세요.", "Transfira modelos para executar o reconhecimento de voz localmente."),
  "Download GGUF models for fully local language inference on this device.": copy("Download GGUF models for fully local language inference on this device.", "下载 GGUF 模型，在此设备上完全本地运行语言推理。", "Descarga modelos GGUF para inferencia local en el dispositivo.", "Téléchargez des modèles GGUF pour l’inférence locale sur l’appareil.", "GGUF-Modelle für vollständig lokale Sprachinferenz herunterladen.", "この端末内で言語推論を実行するGGUFモデルをダウンロードします。", "이 기기에서 언어 추론을 완전히 로컬로 실행할 GGUF 모델을 다운로드하세요.", "Transfira modelos GGUF para inferência de linguagem local."),
  "Download voices for private speech synthesis with sherpa-onnx on this device.": copy("Download voices for private speech synthesis with sherpa-onnx on this device.", "下载语音，在此设备上通过 sherpa-onnx 私密合成语音。", "Descarga voces para síntesis privada con sherpa-onnx.", "Téléchargez des voix pour la synthèse privée avec sherpa-onnx.", "Stimmen für private Sprachsynthese mit sherpa-onnx herunterladen.", "sherpa-onnxによる端末内音声合成用の音声をダウンロードします。", "sherpa-onnx를 사용하는 기기 내 비공개 음성 합성용 음성을 다운로드하세요.", "Transfira vozes para síntese privada com sherpa-onnx."),
  Download: copy("Download", "下载", "Descargar", "Télécharger", "Herunterladen", "ダウンロード", "다운로드", "Transferir"),
  Use: copy("Use", "使用", "Usar", "Utiliser", "Verwenden", "使用", "사용", "Usar"),
  Installing: copy("Installing", "正在安装", "Instalando", "Installation", "Wird installiert", "インストール中", "설치 중", "A instalar"),
  "Working…": copy("Working…", "处理中……", "Procesando…", "Traitement…", "Wird verarbeitet …", "処理中…", "처리 중…", "A processar…"),
  "Downloading…": copy("Downloading…", "正在下载……", "Descargando…", "Téléchargement…", "Wird heruntergeladen …", "ダウンロード中…", "다운로드 중…", "A transferir…"),
  "Download failed.": copy("Download failed.", "下载失败。", "Error en la descarga.", "Échec du téléchargement.", "Download fehlgeschlagen.", "ダウンロードに失敗しました。", "다운로드에 실패했습니다.", "Falha na transferência."),
  "Unable to use this model.": copy("Unable to use this model.", "无法使用此模型。", "No se pudo usar este modelo.", "Impossible d’utiliser ce modèle.", "Dieses Modell kann nicht verwendet werden.", "このモデルを使用できません。", "이 모델을 사용할 수 없습니다.", "Não foi possível usar este modelo."),
  "Unable to remove this model.": copy("Unable to remove this model.", "无法移除此模型。", "No se pudo eliminar este modelo.", "Impossible de supprimer ce modèle.", "Dieses Modell kann nicht entfernt werden.", "このモデルを削除できません。", "이 모델을 제거할 수 없습니다.", "Não foi possível remover este modelo."),
  "Unable to load STT models.": copy("Unable to load STT models.", "无法加载语音转文字模型。", "No se pudieron cargar los modelos de voz a texto.", "Impossible de charger les modèles parole-texte.", "Speech-to-Text-Modelle konnten nicht geladen werden.", "音声認識モデルを読み込めませんでした。", "음성-텍스트 모델을 불러올 수 없습니다.", "Não foi possível carregar os modelos de voz para texto."),
  "Unable to load LLM models.": copy("Unable to load LLM models.", "无法加载大语言模型。", "No se pudieron cargar los modelos de lenguaje.", "Impossible de charger les modèles de langage.", "Sprachmodelle konnten nicht geladen werden.", "大規模言語モデルを読み込めませんでした。", "대규모 언어 모델을 불러올 수 없습니다.", "Não foi possível carregar os modelos de linguagem."),
  "Unable to load TTS models.": copy("Unable to load TTS models.", "无法加载文字转语音模型。", "No se pudieron cargar los modelos de texto a voz.", "Impossible de charger les modèles texte-parole.", "Text-to-Speech-Modelle konnten nicht geladen werden.", "音声合成モデルを読み込めませんでした。", "텍스트-음성 모델을 불러올 수 없습니다.", "Não foi possível carregar os modelos de texto para voz."),
  "In use — uninstall another model to switch away from this one.": copy("In use — uninstall another model to switch away from this one.", "正在使用中——请卸载其他模型以切换。", "En uso: desinstala otro modelo para cambiar.", "En cours d’utilisation — désinstallez un autre modèle pour changer.", "In Verwendung — ein anderes Modell deinstallieren, um zu wechseln.", "使用中です。別のモデルをアンインストールして切り替えてください。", "사용 중 — 다른 모델을 제거하여 전환하세요.", "Em uso — desinstale outro modelo para mudar."),
  English: copy("English", "英语", "Inglés", "Anglais", "Englisch", "英語", "영어", "Inglês"),
  Chinese: copy("Chinese", "中文", "Chino", "Chinois", "Chinesisch", "中国語", "중국어", "Chinês"),
  Spanish: copy("Spanish", "西班牙语", "Español", "Espagnol", "Spanisch", "スペイン語", "스페인어", "Espanhol"),
  French: copy("French", "法语", "Francés", "Français", "Französisch", "フランス語", "프랑스어", "Francês"),
  German: copy("German", "德语", "Alemán", "Allemand", "Deutsch", "ドイツ語", "독일어", "Alemão"),
  Japanese: copy("Japanese", "日语", "Japonés", "Japonais", "Japanisch", "日本語", "일본어", "Japonês"),
  Korean: copy("Korean", "韩语", "Coreano", "Coréen", "Koreanisch", "韓国語", "한국어", "Coreano"),
  Portuguese: copy("Portuguese", "葡萄牙语", "Portugués", "Portugais", "Portugiesisch", "ポルトガル語", "포르투갈어", "Português"),
  Multilingual: copy("Multilingual", "多语言", "Multilingüe", "Multilingue", "Mehrsprachig", "多言語", "다국어", "Multilingue"),
  "Multiple voices": copy("Multiple voices", "多种音色", "Varias voces", "Plusieurs voix", "Mehrere Stimmen", "複数の音声", "여러 음성", "Várias vozes"),
  "English (US)": copy("English (US)", "英语（美国）", "Inglés (EE. UU.)", "Anglais (États-Unis)", "Englisch (USA)", "英語（米国）", "영어(미국)", "Inglês (EUA)"),
  "Spanish (Spain)": copy("Spanish (Spain)", "西班牙语（西班牙）", "Español (España)", "Espagnol (Espagne)", "Spanisch (Spanien)", "スペイン語（スペイン）", "스페인어(스페인)", "Espanhol (Espanha)"),
  "French (France)": copy("French (France)", "法语（法国）", "Francés (Francia)", "Français (France)", "Französisch (Frankreich)", "フランス語（フランス）", "프랑스어(프랑스)", "Francês (França)"),
  "German (Germany)": copy("German (Germany)", "德语（德国）", "Alemán (Alemania)", "Allemand (Allemagne)", "Deutsch (Deutschland)", "ドイツ語（ドイツ）", "독일어(독일)", "Alemão (Alemanha)"),
  "Portuguese (Brazil)": copy("Portuguese (Brazil)", "葡萄牙语（巴西）", "Portugués (Brasil)", "Portugais (Brésil)", "Portugiesisch (Brasilien)", "ポルトガル語（ブラジル）", "포르투갈어(브라질)", "Português (Brasil)"),
  "Portuguese (Portugal)": copy("Portuguese (Portugal)", "葡萄牙语（葡萄牙）", "Portugués (Portugal)", "Portugais (Portugal)", "Portugiesisch (Portugal)", "ポルトガル語（ポルトガル）", "포르투갈어(포르투갈)", "Português (Portugal)"),
  "Read aloud": copy("Read aloud", "朗读", "Leer en voz alta", "Lire à voix haute", "Vorlesen", "読み上げる", "소리 내어 읽기", "Ler em voz alta"),
  Stop: copy("Stop", "停止", "Detener", "Arrêter", "Stoppen", "停止", "중지", "Parar"),
  "Open Text-to-Speech Models": copy("Open Text-to-Speech Models", "打开文字转语音模型", "Abrir modelos de texto a voz", "Ouvrir les modèles texte-parole", "Text-to-Speech-Modelle öffnen", "音声合成モデルを開く", "텍스트-음성 모델 열기", "Abrir modelos de texto para voz"),
  "Available when the current local operation finishes.": copy("Available when the current local operation finishes.", "当前本地操作完成后即可使用。", "Disponible cuando finalice la operación local actual.", "Disponible une fois l’opération locale terminée.", "Verfügbar, sobald der aktuelle lokale Vorgang abgeschlossen ist.", "現在のローカル処理が完了すると使用できます。", "현재 로컬 작업이 완료되면 사용할 수 있습니다.", "Disponível quando a operação local atual terminar."),
  "There is no text to read aloud.": copy("There is no text to read aloud.", "没有可朗读的文字。", "No hay texto para leer en voz alta.", "Aucun texte à lire à voix haute.", "Kein Text zum Vorlesen vorhanden.", "読み上げるテキストがありません。", "소리 내어 읽을 텍스트가 없습니다.", "Não há texto para ler em voz alta."),
  "Wait for the current local AI or transcription operation to finish.": copy("Wait for the current local AI or transcription operation to finish.", "请等待当前本地 AI 或转写操作完成。", "Espera a que termine la operación local de IA o transcripción.", "Attendez la fin de l’opération locale d’IA ou de transcription.", "Warte, bis der aktuelle lokale KI- oder Transkriptionsvorgang abgeschlossen ist.", "現在のローカルAIまたは文字起こし処理が完了するまでお待ちください。", "현재 로컬 AI 또는 전사 작업이 완료될 때까지 기다려 주세요.", "Aguarde que a operação local de IA ou transcrição termine."),
  "Preparing speech…": copy("Preparing speech…", "正在准备语音……", "Preparando voz…", "Préparation de la voix…", "Sprachausgabe wird vorbereitet …", "音声を準備中…", "음성 준비 중…", "A preparar voz…"),
  Playing: copy("Playing", "正在播放", "Reproduciendo", "Lecture", "Wiedergabe", "再生中", "재생 중", "A reproduzir"),
  "Download and activate a TTS model first.": copy("Download and activate a TTS model first.", "请先下载并启用一个文字转语音模型。", "Descarga y activa primero un modelo de texto a voz.", "Téléchargez et activez d’abord un modèle texte-parole.", "Zuerst ein Text-to-Speech-Modell herunterladen und aktivieren.", "まず音声合成モデルをダウンロードして有効にしてください。", "먼저 텍스트-음성 모델을 다운로드하고 활성화하세요.", "Transfira e ative primeiro um modelo de texto para voz."),
  "Unable to start speech playback.": copy("Unable to start speech playback.", "无法开始语音播放。", "No se pudo iniciar la reproducción de voz.", "Impossible de démarrer la lecture vocale.", "Sprachwiedergabe konnte nicht gestartet werden.", "音声再生を開始できませんでした。", "음성 재생을 시작할 수 없습니다.", "Não foi possível iniciar a reprodução de voz."),
  "Speech playback failed.": copy("Speech playback failed.", "语音播放失败。", "Error en la reproducción de voz.", "Échec de la lecture vocale.", "Sprachwiedergabe fehlgeschlagen.", "音声再生に失敗しました。", "음성 재생에 실패했습니다.", "Falha na reprodução de voz."),
  "Regenerate Core Insights": copy("Regenerate Core Insights", "重新生成核心洞察", "Regenerar ideas principales", "Régénérer les analyses principales", "Kernerkenntnisse neu erzeugen", "コアインサイトを再生成", "핵심 인사이트 다시 생성", "Gerar novamente informações principais"),
  "Generate Core Insights": copy("Generate Core Insights", "生成核心洞察", "Generar ideas principales", "Générer les analyses principales", "Kernerkenntnisse erzeugen", "コアインサイトを生成", "핵심 인사이트 생성", "Gerar informações principais"),
  "Waiting for local AI…": copy("Waiting for local AI…", "正在等待本地 AI……", "Esperando a la IA local…", "En attente de l’IA locale…", "Warten auf lokale KI …", "ローカルAIを待機中…", "로컬 AI 대기 중…", "A aguardar pela IA local…"),
  "Extracting core insights…": copy("Extracting core insights…", "正在提取核心洞察……", "Extrayendo ideas principales…", "Extraction des analyses principales…", "Kernerkenntnisse werden extrahiert …", "コアインサイトを抽出中…", "핵심 인사이트 추출 중…", "A extrair informações principais…"),
  "Turn this transcript into a note shaped for how you'll use it.": copy("Turn this transcript into a note shaped for how you'll use it.", "根据你的使用场景，将转写内容整理成笔记。", "Convierte la transcripción en una nota adaptada a su uso.", "Transformez cette transcription en une note adaptée à votre usage.", "Dieses Transkript passend zum Verwendungszweck als Notiz strukturieren.", "用途に合わせて文字起こしをノートに整理します。", "사용 목적에 맞게 전사 내용을 노트로 정리하세요.", "Transforme a transcrição numa nota adaptada à sua utilização."),
  "Organizing your knowledge…": copy("Organizing your knowledge…", "正在整理知识……", "Organizando el conocimiento…", "Organisation de vos connaissances…", "Wissen wird organisiert …", "ナレッジを整理中…", "지식 정리 중…", "A organizar o conhecimento…"),
  "Running privately on this device. This can take a moment.": copy("Running privately on this device. This can take a moment.", "正在此设备上私密运行，可能需要一点时间。", "Se ejecuta de forma privada en este dispositivo. Puede tardar un momento.", "Exécution privée sur cet appareil. Cela peut prendre un moment.", "Private Ausführung auf diesem Gerät. Dies kann einen Moment dauern.", "この端末内で処理しています。少し時間がかかる場合があります。", "이 기기에서 비공개로 실행 중이며 잠시 걸릴 수 있습니다.", "Em execução privada neste dispositivo. Pode demorar um pouco."),
  "Choose a scene": copy("Choose a scene", "选择场景", "Elegir un escenario", "Choisir un scénario", "Szenario auswählen", "シーンを選択", "상황 선택", "Escolher um cenário"),
  Regenerate: copy("Regenerate", "重新生成", "Regenerar", "Régénérer", "Neu erzeugen", "再生成", "다시 생성", "Gerar novamente"),
  "Generate Knowledge": copy("Generate Knowledge", "生成知识", "Generar conocimiento", "Générer les connaissances", "Wissen erzeugen", "ナレッジを生成", "지식 생성", "Gerar conhecimento"),
  "Generate again": copy("Generate again", "再次生成", "Generar de nuevo", "Générer à nouveau", "Erneut erzeugen", "もう一度生成", "다시 생성", "Gerar novamente"),
  Meeting: copy("Meeting", "会议", "Reunión", "Réunion", "Besprechung", "会議", "회의", "Reunião"),
  Lecture: copy("Lecture", "讲座", "Clase", "Cours", "Vorlesung", "講義", "강의", "Aula"),
  Consultation: copy("Consultation", "咨询", "Consulta", "Consultation", "Beratung", "相談", "상담", "Consulta"),
  Interview: copy("Interview", "访谈", "Entrevista", "Entretien", "Interview", "インタビュー", "인터뷰", "Entrevista"),
  Brainstorm: copy("Brainstorm", "头脑风暴", "Lluvia de ideas", "Brainstorming", "Brainstorming", "ブレインストーミング", "브레인스토밍", "Brainstorming"),
  General: copy("General", "通用", "General", "Général", "Allgemein", "一般", "일반", "Geral"),
  "Discussion, decisions, alignment, tensions, and unresolved issues": copy("Discussion, decisions, alignment, tensions, and unresolved issues", "讨论、决策、共识、分歧和未解决问题", "Debate, decisiones, acuerdos, tensiones y asuntos pendientes", "Discussion, décisions, alignement, tensions et questions non résolues", "Diskussion, Entscheidungen, Abstimmung, Spannungen und offene Fragen", "議論、決定、合意、対立、未解決事項", "논의, 결정, 합의, 긴장 및 미해결 문제", "Discussão, decisões, alinhamento, tensões e questões por resolver"),
  "Concepts, explanations, examples, relationships, and caveats": copy("Concepts, explanations, examples, relationships, and caveats", "概念、讲解、示例、关联和注意事项", "Conceptos, explicaciones, ejemplos, relaciones y matices", "Concepts, explications, exemples, relations et réserves", "Konzepte, Erklärungen, Beispiele, Beziehungen und Einschränkungen", "概念、説明、例、関係、注意点", "개념, 설명, 예시, 관계 및 주의 사항", "Conceitos, explicações, exemplos, relações e ressalvas"),
  "Situation, professional guidance, rationale, options, and cautions": copy("Situation, professional guidance, rationale, options, and cautions", "情况、专业建议、依据、选项和注意事项", "Situación, orientación profesional, razones, opciones y precauciones", "Situation, conseils professionnels, justification, options et précautions", "Situation, fachliche Beratung, Begründung, Optionen und Hinweise", "状況、専門的助言、根拠、選択肢、注意事項", "상황, 전문 조언, 근거, 선택지 및 주의 사항", "Situação, orientação profissional, fundamentos, opções e cuidados"),
  "Perspectives, behavior, needs, motivations, and supported patterns": copy("Perspectives, behavior, needs, motivations, and supported patterns", "观点、行为、需求、动机和有依据的规律", "Perspectivas, comportamiento, necesidades, motivaciones y patrones respaldados", "Points de vue, comportement, besoins, motivations et tendances étayées", "Perspektiven, Verhalten, Bedürfnisse, Motivation und belegte Muster", "視点、行動、ニーズ、動機、裏付けられたパターン", "관점, 행동, 요구, 동기 및 근거 있는 패턴", "Perspetivas, comportamento, necessidades, motivações e padrões sustentados"),
  "Ideas, alternatives, connections, evaluation, and open questions": copy("Ideas, alternatives, connections, evaluation, and open questions", "想法、替代方案、关联、评估和开放问题", "Ideas, alternativas, conexiones, evaluación y preguntas abiertas", "Idées, alternatives, liens, évaluation et questions ouvertes", "Ideen, Alternativen, Verbindungen, Bewertung und offene Fragen", "アイデア、代替案、つながり、評価、未解決の質問", "아이디어, 대안, 연결, 평가 및 열린 질문", "Ideias, alternativas, ligações, avaliação e questões em aberto"),
  "Context, evidence, relationships, nuance, and reference details": copy("Context, evidence, relationships, nuance, and reference details", "背景、证据、关联、细节差异和参考信息", "Contexto, pruebas, relaciones, matices y detalles de referencia", "Contexte, éléments probants, relations, nuances et détails de référence", "Kontext, Belege, Beziehungen, Nuancen und Referenzdetails", "背景、根拠、関係、ニュアンス、参考情報", "맥락, 근거, 관계, 뉘앙스 및 참고 세부 정보", "Contexto, evidências, relações, nuances e detalhes de referência"),
};

const ZH_MODEL_DESCRIPTIONS: Record<string, string> = {
  "Llama 1B general-purpose multilingual instruction model for compact text generation.": "Llama 1B 通用多语言指令模型，适合轻量文本生成。",
  "Larger 3B instruction-tuned candidate from the multilingual Llama 3.2 family.": "来自多语言 Llama 3.2 系列的较大 3B 指令微调模型。",
  "Current-generation 1B multilingual Gemma instruction model for text generation.": "新一代 1B 多语言 Gemma 指令模型，用于文本生成。",
  "Microsoft's approximately 3.8B-parameter multilingual general instruction model.": "微软约 38 亿参数的多语言通用指令模型。",
  "LFM 1.2B general instruction model designed for compact and on-device deployment.": "LFM 1.2B 通用指令模型，专为轻量和设备端部署设计。",
  "High-resource 8B boundary candidate reserved for on-device feasibility testing.": "资源需求较高的 8B 边界候选模型，用于设备端可行性测试。",
  "Default multilingual model for broad language coverage.": "默认多语言模型，覆盖多种语言。",
  "Recommended Chinese model with compact INT8 weights and English support.": "推荐的中文模型，采用轻量 INT8 权重并支持英语。",
  "Full-precision Chinese and English alternative.": "全精度中英双语备选模型。",
  "Bilingual alternative based on the Matcha architecture.": "基于 Matcha 架构的双语备选模型。",
  "Dedicated Mandarin voice and the preferred compact Piper option.": "专用普通话音色，也是推荐的轻量 Piper 选项。",
  "Dedicated Mandarin backup voice.": "专用普通话备用音色。",
  "Compact US English voice with a good quality and speed balance.": "轻量美式英语音色，兼顾质量与速度。",
  "Higher-quality US English voice for devices with more storage.": "质量更高的美式英语音色，适合存储空间较大的设备。",
  "Dedicated Spanish voice.": "专用西班牙语音色。",
  "Dedicated French voice.": "专用法语音色。",
  "Compact dedicated German voice.": "轻量专用德语音色。",
  "Higher-quality German voice for devices with more storage.": "质量更高的德语音色，适合存储空间较大的设备。",
  "Dedicated Brazilian Portuguese voice.": "专用巴西葡萄牙语音色。",
  "Dedicated European Portuguese voice.": "专用欧洲葡萄牙语音色。",
};

export function translateUiCopy(value: string, language: UiLanguage): string {
  const exact = UI_COPY[value]?.[language];
  if (exact) return exact;

  if (language === "zh-CN") {
    const modelDescription = ZH_MODEL_DESCRIPTIONS[value];
    if (modelDescription) return modelDescription;

    const whisper = value.match(/^Multilingual Whisper (.+) speech recognition model \((.+)\)\.$/);
    if (whisper) return `多语言 Whisper ${whisper[1]} 语音识别模型（${whisper[2]}）。`;
    const parakeet = value.match(/^NVIDIA Parakeet TDT 0\.6B v3 speech recognition model \((.+)\)\.$/);
    if (parakeet) return `NVIDIA Parakeet TDT 0.6B v3 语音识别模型（${parakeet[1]}）。`;
  }

  const templateSections = value.match(/^(\d+) sections$/);
  if (templateSections) return ({ en: `${templateSections[1]} section${templateSections[1] === "1" ? "" : "s"}`, "zh-CN": `${templateSections[1]} 个分区`, es: `${templateSections[1]} secciones`, fr: `${templateSections[1]} sections`, de: `${templateSections[1]} Abschnitte`, ja: `${templateSections[1]}セクション`, ko: `${templateSections[1]}개 섹션`, pt: `${templateSections[1]} secções` })[language];

  const reviewSections = value.match(/^Review sections \((\d+)\/8\)$/);
  if (reviewSections) return ({ en: value, "zh-CN": `检查分区（${reviewSections[1]}/8）`, es: `Revisar secciones (${reviewSections[1]}/8)`, fr: `Vérifier les sections (${reviewSections[1]}/8)`, de: `Abschnitte prüfen (${reviewSections[1]}/8)`, ja: `セクションを確認（${reviewSections[1]}/8）`, ko: `섹션 검토 (${reviewSections[1]}/8)`, pt: `Rever secções (${reviewSections[1]}/8)` })[language];

  const sectionNumber = value.match(/^Section (\d+)$/);
  if (sectionNumber) return ({ en: value, "zh-CN": `分区 ${sectionNumber[1]}`, es: `Sección ${sectionNumber[1]}`, fr: `Section ${sectionNumber[1]}`, de: `Abschnitt ${sectionNumber[1]}`, ja: `セクション ${sectionNumber[1]}`, ko: `섹션 ${sectionNumber[1]}`, pt: `Secção ${sectionNumber[1]}` })[language];

  const movedTemplate = value.match(/^(.+) moved to Trash$/);
  if (movedTemplate) return ({ en: value, "zh-CN": `${movedTemplate[1]} 已移到废纸篓`, es: `${movedTemplate[1]} se movió a la papelera`, fr: `${movedTemplate[1]} a été déplacé vers la corbeille`, de: `${movedTemplate[1]} wurde in den Papierkorb verschoben`, ja: `${movedTemplate[1]}をゴミ箱に移動しました`, ko: `${movedTemplate[1]}이(가) 휴지통으로 이동됨`, pt: `${movedTemplate[1]} foi movido para o lixo` })[language];

  const selectedTranscripts = value.match(/^(\d+) selected transcripts?$/);
  if (selectedTranscripts) return ({ en: `${selectedTranscripts[1]} selected transcript${selectedTranscripts[1] === "1" ? "" : "s"}`, "zh-CN": `已选择 ${selectedTranscripts[1]} 篇转写`, es: `${selectedTranscripts[1]} transcripciones seleccionadas`, fr: `${selectedTranscripts[1]} transcriptions sélectionnées`, de: `${selectedTranscripts[1]} Transkripte ausgewählt`, ja: `${selectedTranscripts[1]}件の文字起こしを選択`, ko: `전사 ${selectedTranscripts[1]}개 선택됨`, pt: `${selectedTranscripts[1]} transcrições selecionadas` })[language];

  const moveConversation = value.match(/^Move (.+) to Trash$/);
  if (moveConversation) return ({ en: value, "zh-CN": `将 ${moveConversation[1]} 移到废纸篓`, es: `Mover ${moveConversation[1]} a la papelera`, fr: `Déplacer ${moveConversation[1]} vers la corbeille`, de: `${moveConversation[1]} in den Papierkorb verschieben`, ja: `${moveConversation[1]}をゴミ箱に移動`, ko: `${moveConversation[1]}을(를) 휴지통으로 이동`, pt: `Mover ${moveConversation[1]} para o lixo` })[language];

  const shown = value.match(/^(\d+) shown$/);
  if (shown) return ({ en: `${shown[1]} shown`, "zh-CN": `显示 ${shown[1]} 条`, es: `${shown[1]} mostradas`, fr: `${shown[1]} affichées`, de: `${shown[1]} angezeigt`, ja: `${shown[1]}件表示`, ko: `${shown[1]}개 표시`, pt: `${shown[1]} apresentadas` })[language];

  const thisWeek = value.match(/^\+(\S+) this week$/);
  if (thisWeek) return ({ en: `+${thisWeek[1]} this week`, "zh-CN": `本周 +${thisWeek[1]}`, es: `+${thisWeek[1]} esta semana`, fr: `+${thisWeek[1]} cette semaine`, de: `+${thisWeek[1]} diese Woche`, ja: `今週 +${thisWeek[1]}`, ko: `이번 주 +${thisWeek[1]}`, pt: `+${thisWeek[1]} esta semana` })[language];

  const completed = value.match(/^Completed \((\d+)\)$/);
  if (completed) return ({ en: `Completed (${completed[1]})`, "zh-CN": `已完成（${completed[1]}）`, es: `Completadas (${completed[1]})`, fr: `Terminées (${completed[1]})`, de: `Erledigt (${completed[1]})`, ja: `完了（${completed[1]}）`, ko: `완료됨 (${completed[1]})`, pt: `Concluídas (${completed[1]})` })[language];

  const openNotes = value.match(/^(\d+) open notes?$/);
  if (openNotes) return ({ en: `${openNotes[1]} open note${openNotes[1] === "1" ? "" : "s"}`, "zh-CN": `${openNotes[1]} 篇待处理笔记`, es: `${openNotes[1]} nota${openNotes[1] === "1" ? "" : "s"} abierta${openNotes[1] === "1" ? "" : "s"}`, fr: `${openNotes[1]} note${openNotes[1] === "1" ? "" : "s"} en attente`, de: `${openNotes[1]} offene Notiz${openNotes[1] === "1" ? "" : "en"}`, ja: `${openNotes[1]}件の未処理ノート`, ko: `미처리 노트 ${openNotes[1]}개`, pt: `${openNotes[1]} nota${openNotes[1] === "1" ? "" : "s"} em aberto` })[language];

  const downloading = value.match(/^Downloading…\s?(\d+)%$/);
  if (downloading) return ({ en: `Downloading… ${downloading[1]}%`, "zh-CN": `正在下载…… ${downloading[1]}%`, es: `Descargando… ${downloading[1]}%`, fr: `Téléchargement… ${downloading[1]}%`, de: `Wird heruntergeladen … ${downloading[1]}%`, ja: `ダウンロード中… ${downloading[1]}%`, ko: `다운로드 중… ${downloading[1]}%`, pt: `A transferir… ${downloading[1]}%` })[language];

  const removeModel = value.match(/^Remove "(.+)" from this device\?$/);
  if (removeModel) return ({ en: `Remove "${removeModel[1]}" from this device?`, "zh-CN": `要从此设备移除“${removeModel[1]}”吗？`, es: `¿Eliminar "${removeModel[1]}" de este dispositivo?`, fr: `Supprimer « ${removeModel[1]} » de cet appareil ?`, de: `„${removeModel[1]}“ von diesem Gerät entfernen?`, ja: `「${removeModel[1]}」をこの端末から削除しますか？`, ko: `이 기기에서 “${removeModel[1]}” 모델을 제거할까요?`, pt: `Remover "${removeModel[1]}" deste dispositivo?` })[language];

  const voices = value.match(/^(\d+) voice(s)?$/);
  if (voices) return ({ en: value, "zh-CN": `${voices[1]} 种音色`, es: `${voices[1]} ${voices[2] ? "voces" : "voz"}`, fr: `${voices[1]} voix`, de: `${voices[1]} Stimme${voices[2] ? "n" : ""}`, ja: `${voices[1]}音声`, ko: `${voices[1]}개 음성`, pt: `${voices[1]} ${voices[2] ? "vozes" : "voz"}` })[language];

  return value;
}
