import type { UiLanguage } from "@/localization/i18n";

type Copy = Record<UiLanguage, string>;

const copy = (en: string, zh: string, es: string, fr: string, de: string, ja: string, ko: string, pt: string): Copy => ({
  en, "zh-CN": zh, es, fr, de, ja, ko, pt,
});

const UI_COPY: Record<string, Copy> = {
  "Try again": copy("Try again", "重试", "Reintentar", "Réessayer", "Erneut versuchen", "もう一度試す", "다시 시도", "Tentar novamente"),
  Workspaces: copy("Workspaces", "工作区", "Espacios", "Espaces", "Arbeitsbereiche", "ワークスペース", "작업 공간", "Espaços"),
  "Browse and organize your saved notes.": copy("Browse and organize your saved notes.", "浏览并整理已保存的笔记。", "Explora y organiza tus notas guardadas.", "Parcourez et organisez vos notes enregistrées.", "Gespeicherte Notizen durchsuchen und organisieren.", "保存したノートを閲覧・整理します。", "저장된 노트를 찾아보고 정리하세요.", "Explore e organize as notas guardadas."),
  "Start a transcription": copy("Start a transcription", "开始转写", "Iniciar una transcripción", "Démarrer une transcription", "Transkription starten", "文字起こしを開始", "전사 시작", "Iniciar uma transcrição"),
  "Choose live recording or upload an audio file.": copy("Choose live recording or upload an audio file.", "选择实时录音或上传音频文件。", "Elige grabación en directo o sube un archivo de audio.", "Choisissez l’enregistrement en direct ou importez un fichier audio.", "Live-Aufnahme wählen oder Audiodatei hochladen.", "ライブ録音または音声ファイルを選択します。", "실시간 녹음 또는 오디오 파일 업로드를 선택하세요.", "Escolha gravação em direto ou carregue um ficheiro de áudio."),
  "Live recording": copy("Live recording", "实时录音", "Grabación en directo", "Enregistrement en direct", "Live-Aufnahme", "ライブ録音", "실시간 녹음", "Gravação em direto"),
  "Record and transcribe as you speak.": copy("Record and transcribe as you speak.", "边说边录音和转写。", "Graba y transcribe mientras hablas.", "Enregistrez et transcrivez pendant que vous parlez.", "Beim Sprechen aufnehmen und transkribieren.", "話しながら録音・文字起こしします。", "말하면서 녹음하고 전사하세요.", "Grave e transcreva enquanto fala."),
  "Upload audio": copy("Upload audio", "上传音频", "Subir audio", "Importer un audio", "Audio hochladen", "音声をアップロード", "오디오 업로드", "Carregar áudio"),
  "Choose a file and start transcribing.": copy("Choose a file and start transcribing.", "选择文件并开始转写。", "Elige un archivo y empieza a transcribir.", "Choisissez un fichier et lancez la transcription.", "Datei wählen und Transkription starten.", "ファイルを選択して文字起こしを開始します。", "파일을 선택하고 전사를 시작하세요.", "Escolha um ficheiro e comece a transcrever."),
  Overview: copy("Overview", "概览", "Resumen", "Aperçu", "Übersicht", "概要", "개요", "Visão geral"),
  "Your notes and upcoming moments at a glance.": copy("Your notes and upcoming moments at a glance.", "一览笔记和即将到来的事项。", "Tus notas y próximos momentos de un vistazo.", "Vos notes et événements à venir en un coup d’œil.", "Notizen und anstehende Termine auf einen Blick.", "ノートと今後の予定を一覧できます。", "노트와 예정된 일정을 한눈에 확인하세요.", "As suas notas e próximos momentos num relance."),
  Notes: copy("Notes", "笔记", "Notas", "Notes", "Notizen", "ノート", "노트", "Notas"),
  Calendar: copy("Calendar", "日历", "Calendario", "Calendrier", "Kalender", "カレンダー", "캘린더", "Calendário"),
  "No calendar items for this date.": copy("No calendar items for this date.", "该日期没有日历事项。", "No hay elementos para esta fecha.", "Aucun élément à cette date.", "Keine Kalendereinträge für dieses Datum.", "この日の予定はありません。", "이 날짜에는 일정이 없습니다.", "Não há itens para esta data."),
  "Local-first · Your data stays on this device": copy("Local-first · Your data stays on this device", "本地优先 · 数据始终保留在此设备上", "Local primero · Tus datos permanecen en este dispositivo", "Local d’abord · Vos données restent sur cet appareil", "Lokal zuerst · Deine Daten bleiben auf diesem Gerät", "ローカル優先 · データはこの端末内に保存", "로컬 우선 · 데이터는 이 기기에만 저장", "Local primeiro · Os dados ficam neste dispositivo"),
  Tasks: copy("Tasks", "任务", "Tareas", "Tâches", "Aufgaben", "タスク", "작업", "Tarefas"),
  "No open tasks": copy("No open tasks", "没有待办任务", "No hay tareas abiertas", "Aucune tâche ouverte", "Keine offenen Aufgaben", "未完了のタスクはありません", "진행 중인 작업 없음", "Sem tarefas em aberto"),
  "Tasks generated from Structured Notes will appear here.": copy("Tasks generated from Structured Notes will appear here.", "从结构化笔记生成的任务会显示在这里。", "Las tareas de notas estructuradas aparecerán aquí.", "Les tâches issues des notes structurées apparaîtront ici.", "Aufgaben aus strukturierten Notizen erscheinen hier.", "構造化ノートから生成されたタスクがここに表示されます。", "구조화된 노트에서 생성된 작업이 여기에 표시됩니다.", "As tarefas de notas estruturadas aparecem aqui."),
  "Ask AI": copy("Ask AI", "询问 AI", "Preguntar a la IA", "Demander à l’IA", "KI fragen", "AIに質問", "AI에게 질문", "Perguntar à IA"),
  Manage: copy("Manage", "管理", "Gestionar", "Gérer", "Verwalten", "管理", "관리", "Gerir"),
  "Speech-to-Text Models": copy("Speech-to-Text Models", "语音转文字模型", "Modelos de voz a texto", "Modèles parole-texte", "Speech-to-Text-Modelle", "音声認識モデル", "음성-텍스트 모델", "Modelos de voz para texto"),
  "Large Language Models": copy("Large Language Models", "大语言模型", "Modelos de lenguaje", "Grands modèles de langage", "Große Sprachmodelle", "大規模言語モデル", "대규모 언어 모델", "Grandes modelos de linguagem"),
  "Text-to-Speech Models": copy("Text-to-Speech Models", "文字转语音模型", "Modelos de texto a voz", "Modèles texte-parole", "Text-to-Speech-Modelle", "音声合成モデル", "텍스트-음성 모델", "Modelos de texto para voz"),
  Active: copy("Active", "已启用", "Activo", "Actif", "Aktiv", "有効", "활성", "Ativo"),
  Downloading: copy("Downloading", "正在下载", "Descargando", "Téléchargement", "Wird heruntergeladen", "ダウンロード中", "다운로드 중", "A transferir"),
  "In use — switch models before uninstalling this one.": copy("In use — switch models before uninstalling this one.", "正在使用中，请先切换模型再卸载。", "En uso: cambia de modelo antes de desinstalarlo.", "En cours d’utilisation — changez de modèle avant de le désinstaller.", "In Verwendung — vor der Deinstallation Modell wechseln.", "使用中です。アンインストール前にモデルを切り替えてください。", "사용 중 — 제거하기 전에 모델을 전환하세요.", "Em uso — mude de modelo antes de desinstalar."),
  "Currently used for local speech synthesis.": copy("Currently used for local speech synthesis.", "当前用于本地语音合成。", "Se usa para síntesis de voz local.", "Utilisé pour la synthèse vocale locale.", "Wird für lokale Sprachsynthese verwendet.", "ローカル音声合成に使用中です。", "현재 로컬 음성 합성에 사용 중입니다.", "Usado atualmente para síntese de voz local."),
  "Audio and transcription stay on this device.": copy("Audio and transcription stay on this device.", "音频和转写内容仅保留在此设备上。", "El audio y la transcripción permanecen en este dispositivo.", "L’audio et la transcription restent sur cet appareil.", "Audio und Transkription bleiben auf diesem Gerät.", "音声と文字起こしはこの端末内に保存されます。", "오디오와 전사 내용은 이 기기에만 저장됩니다.", "O áudio e a transcrição ficam neste dispositivo."),
  "Start recording": copy("Start recording", "开始录音", "Iniciar grabación", "Démarrer l’enregistrement", "Aufnahme starten", "録音を開始", "녹음 시작", "Iniciar gravação"),
  "Tap the button to begin live transcription": copy("Tap the button to begin live transcription", "点击按钮开始实时转写", "Pulsa el botón para iniciar la transcripción", "Touchez le bouton pour lancer la transcription", "Tippe auf die Schaltfläche, um zu starten", "ボタンをタップして文字起こしを開始", "버튼을 눌러 실시간 전사를 시작하세요", "Toque no botão para iniciar a transcrição"),
  Finish: copy("Finish", "完成", "Finalizar", "Terminer", "Beenden", "完了", "완료", "Terminar"),
  "Save transcription": copy("Save transcription", "保存转写", "Guardar transcripción", "Enregistrer la transcription", "Transkription speichern", "文字起こしを保存", "전사 저장", "Guardar transcrição"),
  Discard: copy("Discard", "丢弃", "Descartar", "Supprimer", "Verwerfen", "破棄", "버리기", "Descartar"),
  "Note name": copy("Note name", "笔记名称", "Nombre de la nota", "Nom de la note", "Notizname", "ノート名", "노트 이름", "Nome da nota"),
  Workspace: copy("Workspace", "工作区", "Espacio", "Espace", "Arbeitsbereich", "ワークスペース", "작업 공간", "Espaço"),
  "Choose an audio file": copy("Choose an audio file", "选择音频文件", "Elegir un archivo de audio", "Choisir un fichier audio", "Audiodatei auswählen", "音声ファイルを選択", "오디오 파일 선택", "Escolher um ficheiro de áudio"),
  "Recording audio": copy("Recording audio", "录音音频", "Audio grabado", "Audio enregistré", "Audioaufnahme", "録音音声", "녹음 오디오", "Áudio gravado"),
  Play: copy("Play", "播放", "Reproducir", "Lire", "Abspielen", "再生", "재생", "Reproduzir"),
  Pause: copy("Pause", "暂停", "Pausa", "Pause", "Pause", "一時停止", "일시 정지", "Pausa"),
  "Tap to listen": copy("Tap to listen", "点击收听", "Pulsa para escuchar", "Touchez pour écouter", "Zum Anhören tippen", "タップして再生", "탭하여 듣기", "Toque para ouvir"),
  "Playing on this device": copy("Playing on this device", "正在此设备上播放", "Reproduciendo en este dispositivo", "Lecture sur cet appareil", "Wiedergabe auf diesem Gerät", "この端末で再生中", "이 기기에서 재생 중", "A reproduzir neste dispositivo"),
  "Structured Note": copy("Structured Note", "结构化笔记", "Nota estructurada", "Note structurée", "Strukturierte Notiz", "構造化ノート", "구조화된 노트", "Nota estruturada"),
  Summary: copy("Summary", "摘要", "Resumen", "Résumé", "Zusammenfassung", "要約", "요약", "Resumo"),
  "Key Points": copy("Key Points", "要点", "Puntos clave", "Points clés", "Kernpunkte", "要点", "핵심 사항", "Pontos-chave"),
  Reminders: copy("Reminders", "提醒", "Recordatorios", "Rappels", "Erinnerungen", "リマインダー", "알림", "Lembretes"),
  "Calendar Intents": copy("Calendar Intents", "日历事项", "Intenciones de calendario", "Intentions de calendrier", "Kalenderabsichten", "カレンダー予定", "캘린더 일정", "Intenções de calendário"),
  Close: copy("Close", "关闭", "Cerrar", "Fermer", "Schließen", "閉じる", "닫기", "Fechar"),
  "No other workspace is available.": copy("No other workspace is available.", "没有其他可用的工作区。", "No hay otro espacio disponible.", "Aucun autre espace n’est disponible.", "Kein anderer Arbeitsbereich verfügbar.", "他に利用できるワークスペースはありません。", "사용 가능한 다른 작업 공간이 없습니다.", "Não há outro espaço disponível."),
  "No actionable steps generated.": copy("No actionable steps generated.", "未生成可执行步骤。", "No se generaron pasos accionables.", "Aucune étape exploitable générée.", "Keine umsetzbaren Schritte erzeugt.", "実行可能な手順は生成されませんでした。", "실행 가능한 단계가 생성되지 않았습니다.", "Não foram gerados passos acionáveis."),
  "Unable to copy. Please try again.": copy("Unable to copy. Please try again.", "无法复制，请重试。", "No se pudo copiar. Inténtalo de nuevo.", "Impossible de copier. Réessayez.", "Kopieren nicht möglich. Bitte erneut versuchen.", "コピーできませんでした。もう一度お試しください。", "복사할 수 없습니다. 다시 시도하세요.", "Não foi possível copiar. Tente novamente."),
  Cancel: copy("Cancel", "取消", "Cancelar", "Annuler", "Abbrechen", "キャンセル", "취소", "Cancelar"),
  Delete: copy("Delete", "删除", "Eliminar", "Supprimer", "Löschen", "削除", "삭제", "Eliminar"),
  Save: copy("Save", "保存", "Guardar", "Enregistrer", "Speichern", "保存", "저장", "Guardar"),
  Create: copy("Create", "创建", "Crear", "Créer", "Erstellen", "作成", "만들기", "Criar"),
  Rename: copy("Rename", "重命名", "Cambiar nombre", "Renommer", "Umbenennen", "名前を変更", "이름 변경", "Mudar nome"),
  Move: copy("Move", "移动", "Mover", "Déplacer", "Verschieben", "移動", "이동", "Mover"),
  Uninstall: copy("Uninstall", "卸载", "Desinstalar", "Désinstaller", "Deinstallieren", "アンインストール", "제거", "Desinstalar"),
  "Uninstall model": copy("Uninstall model", "卸载模型", "Desinstalar modelo", "Désinstaller le modèle", "Modell deinstallieren", "モデルをアンインストール", "모델 제거", "Desinstalar modelo"),
  "Delete note?": copy("Delete note?", "删除笔记？", "¿Eliminar la nota?", "Supprimer la note ?", "Notiz löschen?", "ノートを削除しますか？", "노트를 삭제할까요?", "Eliminar nota?"),
  "Delete workspace?": copy("Delete workspace?", "删除工作区？", "¿Eliminar el espacio?", "Supprimer l’espace ?", "Arbeitsbereich löschen?", "ワークスペースを削除しますか？", "작업 공간을 삭제할까요?", "Eliminar espaço?"),
  "Unable to delete note": copy("Unable to delete note", "无法删除笔记", "No se pudo eliminar la nota", "Impossible de supprimer la note", "Notiz konnte nicht gelöscht werden", "ノートを削除できませんでした", "노트를 삭제할 수 없습니다", "Não foi possível eliminar a nota"),
  "Unable to delete workspace": copy("Unable to delete workspace", "无法删除工作区", "No se pudo eliminar el espacio", "Impossible de supprimer l’espace", "Arbeitsbereich konnte nicht gelöscht werden", "ワークスペースを削除できませんでした", "작업 공간을 삭제할 수 없습니다", "Não foi possível eliminar o espaço"),
  "Please try again.": copy("Please try again.", "请重试。", "Inténtalo de nuevo.", "Veuillez réessayer.", "Bitte erneut versuchen.", "もう一度お試しください。", "다시 시도하세요.", "Tente novamente."),
  "Finish transcription?": copy("Finish transcription?", "完成转写？", "¿Finalizar la transcripción?", "Terminer la transcription ?", "Transkription beenden?", "文字起こしを終了しますか？", "전사를 완료할까요?", "Terminar a transcrição?"),
  "Two-hour limit reached": copy("Two-hour limit reached", "已达到两小时上限", "Se alcanzó el límite de dos horas", "Limite de deux heures atteinte", "Zwei-Stunden-Limit erreicht", "2時間の上限に達しました", "2시간 제한에 도달했습니다", "Limite de duas horas atingido"),
  "e.g. Personal": copy("e.g. Personal", "例如：个人", "p. ej., Personal", "ex. Personnel", "z. B. Persönlich", "例：個人", "예: 개인", "ex.: Pessoal"),
  "e.g. Weekly planning": copy("e.g. Weekly planning", "例如：每周计划", "p. ej., Planificación semanal", "ex. Planification hebdomadaire", "z. B. Wochenplanung", "例：週間計画", "예: 주간 계획", "ex.: Planeamento semanal"),
  "e.g. Interview recording": copy("e.g. Interview recording", "例如：访谈录音", "p. ej., Grabación de entrevista", "ex. Enregistrement d’entretien", "z. B. Interviewaufnahme", "例：インタビュー録音", "예: 인터뷰 녹음", "ex.: Gravação de entrevista"),
  "Workspace name": copy("Workspace name", "工作区名称", "Nombre del espacio", "Nom de l’espace", "Name des Arbeitsbereichs", "ワークスペース名", "작업 공간 이름", "Nome do espaço"),
  "Write the note transcript...": copy("Write the note transcript...", "输入笔记转写内容……", "Escribe la transcripción de la nota...", "Écrivez la transcription de la note…", "Notiztranskript eingeben …", "ノートの文字起こしを入力…", "노트 전사 내용을 입력하세요...", "Escreva a transcrição da nota..."),
  "Note title": copy("Note title", "笔记标题", "Título de la nota", "Titre de la note", "Notiztitel", "ノートのタイトル", "노트 제목", "Título da nota"),
  "Search titles and transcripts": copy("Search titles and transcripts", "搜索标题和转写内容", "Buscar títulos y transcripciones", "Rechercher dans les titres et transcriptions", "Titel und Transkripte durchsuchen", "タイトルと文字起こしを検索", "제목 및 전사 검색", "Pesquisar títulos e transcrições"),
  "Search your notes": copy("Search your notes", "搜索笔记", "Busca en tus notas", "Recherchez dans vos notes", "Notizen durchsuchen", "ノートを検索", "노트 검색", "Pesquise nas suas notas"),
  "No notes found": copy("No notes found", "未找到笔记", "No se encontraron notas", "Aucune note trouvée", "Keine Notizen gefunden", "ノートが見つかりません", "노트를 찾을 수 없습니다", "Não foram encontradas notas"),
  Transcript: copy("Transcript", "转写", "Transcripción", "Transcription", "Transkript", "文字起こし", "전사", "Transcrição"),
  Insights: copy("Insights", "洞察", "Ideas", "Analyses", "Erkenntnisse", "インサイト", "인사이트", "Informações"),
  Knowledge: copy("Knowledge", "知识", "Conocimiento", "Connaissances", "Wissen", "ナレッジ", "지식", "Conhecimento"),
  "Key points": copy("Key points", "要点", "Puntos clave", "Points clés", "Kernpunkte", "要点", "핵심 사항", "Pontos-chave"),
  "Tasks & Action Plan": copy("Tasks & Action Plan", "任务与行动计划", "Tareas y plan de acción", "Tâches et plan d’action", "Aufgaben und Aktionsplan", "タスクと行動計画", "작업 및 실행 계획", "Tarefas e plano de ação"),
  "Summary, key points, tasks, reminders, and calendar events.": copy("Summary, key points, tasks, reminders, and calendar events.", "摘要、要点、任务、提醒和日历事项。", "Resumen, puntos clave, tareas, recordatorios y eventos.", "Résumé, points clés, tâches, rappels et événements.", "Zusammenfassung, Kernpunkte, Aufgaben, Erinnerungen und Termine.", "要約、要点、タスク、リマインダー、予定。", "요약, 핵심 사항, 작업, 알림 및 일정.", "Resumo, pontos-chave, tarefas, lembretes e eventos."),
  "Running privately on this device.": copy("Running privately on this device.", "正在此设备上私密运行。", "Se ejecuta de forma privada en este dispositivo.", "Exécution privée sur cet appareil.", "Private Ausführung auf diesem Gerät.", "この端末内でプライベートに実行中。", "이 기기에서 비공개로 실행 중입니다.", "Em execução privada neste dispositivo."),
  Copied: copy("Copied", "已复制", "Copiado", "Copié", "Kopiert", "コピー済み", "복사됨", "Copiado"),
  "Copy insights": copy("Copy insights", "复制洞察", "Copiar ideas", "Copier les analyses", "Erkenntnisse kopieren", "インサイトをコピー", "인사이트 복사", "Copiar informações"),
  "No supported scenario-specific information was found in this note.": copy("No supported scenario-specific information was found in this note.", "此笔记中未找到支持的场景特定信息。", "No se encontró información específica compatible.", "Aucune information spécifique prise en charge n’a été trouvée.", "Keine unterstützten szenariospezifischen Informationen gefunden.", "対応するシナリオ固有の情報はありません。", "지원되는 시나리오별 정보를 찾지 못했습니다.", "Não foi encontrada informação específica suportada."),
  "Choose an audio file from anywhere on your device. It never leaves this device.": copy("Choose an audio file from anywhere on your device. It never leaves this device.", "从设备中选择音频文件，文件不会离开此设备。", "Elige un archivo de tu dispositivo. Nunca saldrá de él.", "Choisissez un fichier sur votre appareil. Il ne le quitte jamais.", "Audiodatei auf dem Gerät wählen. Sie verlässt es nie.", "端末内の音声ファイルを選択します。外部には送信されません。", "기기에서 오디오 파일을 선택하세요. 파일은 기기 밖으로 전송되지 않습니다.", "Escolha um ficheiro no dispositivo. Nunca sai dele."),
  "No notes yet": copy("No notes yet", "还没有笔记", "Aún no hay notas", "Aucune note", "Noch keine Notizen", "ノートはまだありません", "아직 노트가 없습니다", "Ainda não há notas"),
  "No matching notes": copy("No matching notes", "没有匹配的笔记", "No hay notas coincidentes", "Aucune note correspondante", "Keine passenden Notizen", "一致するノートはありません", "일치하는 노트가 없습니다", "Não há notas correspondentes"),
  "No workspaces yet": copy("No workspaces yet", "还没有工作区", "Aún no hay espacios", "Aucun espace", "Noch keine Arbeitsbereiche", "ワークスペースはまだありません", "아직 작업 공간이 없습니다", "Ainda não há espaços"),
  "Total notes": copy("Total notes", "笔记总数", "Notas totales", "Total des notes", "Notizen gesamt", "ノート総数", "전체 노트", "Total de notas"),
  Pinned: copy("Pinned", "已置顶", "Fijadas", "Épinglées", "Angeheftet", "ピン留め", "고정됨", "Fixadas"),
  Characters: copy("Characters", "字符数", "Caracteres", "Caractères", "Zeichen", "文字数", "문자 수", "Caracteres"),
  "Open tasks": copy("Open tasks", "待办任务", "Tareas abiertas", "Tâches ouvertes", "Offene Aufgaben", "未完了のタスク", "진행 중인 작업", "Tarefas em aberto"),
  "Show all notes": copy("Show all notes", "显示全部笔记", "Mostrar todas las notas", "Afficher toutes les notes", "Alle Notizen anzeigen", "すべてのノートを表示", "모든 노트 보기", "Mostrar todas as notas"),
  "Filter pinned notes": copy("Filter pinned notes", "筛选置顶笔记", "Filtrar notas fijadas", "Filtrer les notes épinglées", "Angeheftete Notizen filtern", "ピン留めノートを絞り込む", "고정된 노트 필터링", "Filtrar notas fixadas"),
  "Filter unfinished notes": copy("Filter unfinished notes", "筛选含未完成任务的笔记", "Filtrar notas sin terminar", "Filtrer les notes non terminées", "Unfertige Notizen filtern", "未完了のノートを絞り込む", "완료되지 않은 노트 필터링", "Filtrar notas por concluir"),
  Overdue: copy("Overdue", "已逾期", "Vencidas", "En retard", "Überfällig", "期限切れ", "기한 지남", "Em atraso"),
  Today: copy("Today", "今天", "Hoy", "Aujourd’hui", "Heute", "今日", "오늘", "Hoje"),
  Upcoming: copy("Upcoming", "即将开始", "Próximas", "À venir", "Anstehend", "今後", "예정", "Próximas"),
  Unscheduled: copy("Unscheduled", "未安排", "Sin programar", "Non planifiées", "Nicht geplant", "未設定", "일정 없음", "Sem data"),
  " open across your Structured Notes": copy(" open across your Structured Notes", " 个待办任务，来自结构化笔记", " abiertas en tus notas estructuradas", " ouvertes dans vos notes structurées", " offen in deinen strukturierten Notizen", "件の未完了タスク（構造化ノート全体）", "개의 진행 중인 작업(구조화된 노트 전체)", " em aberto nas suas notas estruturadas"),
  "+ New workspace": copy("+ New workspace", "+ 新建工作区", "+ Nuevo espacio", "+ Nouvel espace", "+ Neuer Arbeitsbereich", "+ 新しいワークスペース", "+ 새 작업 공간", "+ Novo espaço"),
  "New workspace": copy("New workspace", "新建工作区", "Nuevo espacio", "Nouvel espace", "Neuer Arbeitsbereich", "新しいワークスペース", "새 작업 공간", "Novo espaço"),
  "Create workspace": copy("Create workspace", "创建工作区", "Crear espacio", "Créer l’espace", "Arbeitsbereich erstellen", "ワークスペースを作成", "작업 공간 만들기", "Criar espaço"),
  "Creating...": copy("Creating...", "正在创建……", "Creando...", "Création…", "Wird erstellt …", "作成中…", "만드는 중...", "A criar..."),
  Name: copy("Name", "名称", "Nombre", "Nom", "Name", "名前", "이름", "Nome"),
  "Search notes": copy("Search notes", "搜索笔记", "Buscar notas", "Rechercher des notes", "Notizen suchen", "ノートを検索", "노트 검색", "Pesquisar notas"),
  "Unable to load workspaces.": copy("Unable to load workspaces.", "无法加载工作区。", "No se pudieron cargar los espacios.", "Impossible de charger les espaces.", "Arbeitsbereiche konnten nicht geladen werden.", "ワークスペースを読み込めませんでした。", "작업 공간을 불러올 수 없습니다.", "Não foi possível carregar os espaços."),
  "Unable to create workspace.": copy("Unable to create workspace.", "无法创建工作区。", "No se pudo crear el espacio.", "Impossible de créer l’espace.", "Arbeitsbereich konnte nicht erstellt werden.", "ワークスペースを作成できませんでした。", "작업 공간을 만들 수 없습니다.", "Não foi possível criar o espaço."),
  "+ New note": copy("+ New note", "+ 新建笔记", "+ Nueva nota", "+ Nouvelle note", "+ Neue Notiz", "+ 新しいノート", "+ 새 노트", "+ Nova nota"),
  "＋ New note": copy("＋ New note", "＋ 新建笔记", "＋ Nueva nota", "＋ Nouvelle note", "＋ Neue Notiz", "＋ 新しいノート", "＋ 새 노트", "＋ Nova nota"),
  "New note": copy("New note", "新建笔记", "Nueva nota", "Nouvelle note", "Neue Notiz", "新しいノート", "새 노트", "Nova nota"),
  "Create note": copy("Create note", "创建笔记", "Crear nota", "Créer la note", "Notiz erstellen", "ノートを作成", "노트 만들기", "Criar nota"),
  "Title (optional)": copy("Title (optional)", "标题（可选）", "Título (opcional)", "Titre (facultatif)", "Titel (optional)", "タイトル（任意）", "제목(선택 사항)", "Título (opcional)"),
  "e.g. Team meeting": copy("e.g. Team meeting", "例如：团队会议", "p. ej., Reunión de equipo", "ex. Réunion d’équipe", "z. B. Teambesprechung", "例：チーム会議", "예: 팀 회의", "ex.: Reunião de equipa"),
  "Saving...": copy("Saving...", "正在保存……", "Guardando...", "Enregistrement…", "Wird gespeichert …", "保存中…", "저장 중...", "A guardar..."),
  "Save name": copy("Save name", "保存名称", "Guardar nombre", "Enregistrer le nom", "Namen speichern", "名前を保存", "이름 저장", "Guardar nome"),
  "Rename workspace": copy("Rename workspace", "重命名工作区", "Cambiar nombre del espacio", "Renommer l’espace", "Arbeitsbereich umbenennen", "ワークスペース名を変更", "작업 공간 이름 변경", "Mudar nome do espaço"),
  Done: copy("Done", "完成", "Listo", "Terminé", "Fertig", "完了", "완료", "Concluído"),
  note: copy("note", "条笔记", "nota", "note", "Notiz", "件のノート", "개 노트", "nota"),
  notes: copy("notes", "条笔记", "notas", "notes", "Notizen", "件のノート", "개 노트", "notas"),
  "AI Management": copy("AI Management", "AI 管理", "Gestión de IA", "Gestion de l’IA", "KI-Verwaltung", "AI管理", "AI 관리", "Gestão de IA"),
  "Manage the speech and language models that run locally on this device.": copy("Manage the speech and language models that run locally on this device.", "管理在此设备上本地运行的语音和语言模型。", "Gestiona los modelos de voz y lenguaje que se ejecutan localmente.", "Gérez les modèles vocaux et linguistiques exécutés localement.", "Sprach- und Sprachmodelle verwalten, die lokal auf diesem Gerät laufen.", "この端末でローカル実行される音声・言語モデルを管理します。", "이 기기에서 로컬로 실행되는 음성 및 언어 모델을 관리합니다.", "Gira os modelos de voz e linguagem executados localmente neste dispositivo."),
  "Speech recognition models for local transcription.": copy("Speech recognition models for local transcription.", "用于本地转写的语音识别模型。", "Modelos de reconocimiento de voz para transcripción local.", "Modèles de reconnaissance vocale pour la transcription locale.", "Spracherkennungsmodelle für lokale Transkription.", "ローカル文字起こし用の音声認識モデル。", "로컬 전사용 음성 인식 모델입니다.", "Modelos de reconhecimento de voz para transcrição local."),
  "Language models for private, on-device AI features.": copy("Language models for private, on-device AI features.", "用于私密设备端 AI 功能的语言模型。", "Modelos de lenguaje para funciones de IA privadas en el dispositivo.", "Modèles de langage pour les fonctions d’IA privées sur l’appareil.", "Sprachmodelle für private KI-Funktionen auf dem Gerät.", "端末内で動作するプライベートAI機能用の言語モデル。", "기기 내 비공개 AI 기능을 위한 언어 모델입니다.", "Modelos de linguagem para funcionalidades de IA privadas no dispositivo."),
  "Local voices for private, on-device speech synthesis.": copy("Local voices for private, on-device speech synthesis.", "用于私密设备端语音合成的本地语音。", "Voces locales para síntesis privada en el dispositivo.", "Voix locales pour la synthèse vocale privée sur l’appareil.", "Lokale Stimmen für private Sprachsynthese auf dem Gerät.", "端末内でのプライベート音声合成用ローカル音声。", "기기 내 비공개 음성 합성을 위한 로컬 음성입니다.", "Vozes locais para síntese de voz privada no dispositivo."),
  "Manage speech-to-text models": copy("Manage speech-to-text models", "管理语音转文字模型", "Gestionar modelos de voz a texto", "Gérer les modèles parole-texte", "Speech-to-Text-Modelle verwalten", "音声認識モデルを管理", "음성-텍스트 모델 관리", "Gerir modelos de voz para texto"),
  "Manage large language models": copy("Manage large language models", "管理大语言模型", "Gestionar modelos de lenguaje", "Gérer les grands modèles de langage", "Große Sprachmodelle verwalten", "大規模言語モデルを管理", "대규모 언어 모델 관리", "Gerir grandes modelos de linguagem"),
  "Manage text-to-speech models": copy("Manage text-to-speech models", "管理文字转语音模型", "Gestionar modelos de texto a voz", "Gérer les modèles texte-parole", "Text-to-Speech-Modelle verwalten", "音声合成モデルを管理", "텍스트-음성 모델 관리", "Gerir modelos de texto para voz"),
  "Download models to run speech recognition fully on this device.": copy("Download models to run speech recognition fully on this device.", "下载模型，在此设备上完全本地运行语音识别。", "Descarga modelos para ejecutar el reconocimiento de voz en el dispositivo.", "Téléchargez des modèles pour exécuter la reconnaissance vocale sur l’appareil.", "Modelle für vollständig lokale Spracherkennung herunterladen.", "この端末内で音声認識を実行するモデルをダウンロードします。", "이 기기에서 음성 인식을 완전히 로컬로 실행할 모델을 다운로드하세요.", "Transfira modelos para executar o reconhecimento de voz localmente."),
  "Download GGUF models for fully local language inference on this device.": copy("Download GGUF models for fully local language inference on this device.", "下载 GGUF 模型，在此设备上完全本地运行语言推理。", "Descarga modelos GGUF para inferencia local en el dispositivo.", "Téléchargez des modèles GGUF pour l’inférence locale sur l’appareil.", "GGUF-Modelle für vollständig lokale Sprachinferenz herunterladen.", "この端末内で言語推論を実行するGGUFモデルをダウンロードします。", "이 기기에서 언어 추론을 완전히 로컬로 실행할 GGUF 모델을 다운로드하세요.", "Transfira modelos GGUF para inferência de linguagem local."),
  "Download voices for private speech synthesis with sherpa-onnx on this device.": copy("Download voices for private speech synthesis with sherpa-onnx on this device.", "下载语音，在此设备上通过 sherpa-onnx 私密合成语音。", "Descarga voces para síntesis privada con sherpa-onnx.", "Téléchargez des voix pour la synthèse privée avec sherpa-onnx.", "Stimmen für private Sprachsynthese mit sherpa-onnx herunterladen.", "sherpa-onnxによる端末内音声合成用の音声をダウンロードします。", "sherpa-onnx를 사용하는 기기 내 비공개 음성 합성용 음성을 다운로드하세요.", "Transfira vozes para síntese privada com sherpa-onnx."),
  Download: copy("Download", "下载", "Descargar", "Télécharger", "Herunterladen", "ダウンロード", "다운로드", "Transferir"),
  Use: copy("Use", "使用", "Usar", "Utiliser", "Verwenden", "使用", "사용", "Usar"),
  Installing: copy("Installing", "正在安装", "Instalando", "Installation", "Wird installiert", "インストール中", "설치 중", "A instalar"),
  "Working…": copy("Working…", "处理中……", "Procesando…", "Traitement…", "Wird verarbeitet …", "処理中…", "처리 중…", "A processar…"),
  "Downloading…": copy("Downloading…", "正在下载……", "Descargando…", "Téléchargement…", "Wird heruntergeladen …", "ダウンロード中…", "다운로드 중…", "A transferir…"),
  "Download failed.": copy("Download failed.", "下载失败。", "Error en la descarga.", "Échec du téléchargement.", "Download fehlgeschlagen.", "ダウンロードに失敗しました。", "다운로드에 실패했습니다.", "Falha na transferência."),
  "Unable to use this model.": copy("Unable to use this model.", "无法使用此模型。", "No se pudo usar este modelo.", "Impossible d’utiliser ce modèle.", "Dieses Modell kann nicht verwendet werden.", "このモデルを使用できません。", "이 모델을 사용할 수 없습니다.", "Não foi possível usar este modelo."),
  "Unable to remove this model.": copy("Unable to remove this model.", "无法移除此模型。", "No se pudo eliminar este modelo.", "Impossible de supprimer ce modèle.", "Dieses Modell kann nicht entfernt werden.", "このモデルを削除できません。", "이 모델을 제거할 수 없습니다.", "Não foi possível remover este modelo."),
  "Unable to load STT models.": copy("Unable to load STT models.", "无法加载语音转文字模型。", "No se pudieron cargar los modelos de voz a texto.", "Impossible de charger les modèles parole-texte.", "Speech-to-Text-Modelle konnten nicht geladen werden.", "音声認識モデルを読み込めませんでした。", "음성-텍스트 모델을 불러올 수 없습니다.", "Não foi possível carregar os modelos de voz para texto."),
  "Unable to load LLM models.": copy("Unable to load LLM models.", "无法加载大语言模型。", "No se pudieron cargar los modelos de lenguaje.", "Impossible de charger les modèles de langage.", "Sprachmodelle konnten nicht geladen werden.", "大規模言語モデルを読み込めませんでした。", "대규모 언어 모델을 불러올 수 없습니다.", "Não foi possível carregar os modelos de linguagem."),
  "Unable to load TTS models.": copy("Unable to load TTS models.", "无法加载文字转语音模型。", "No se pudieron cargar los modelos de texto a voz.", "Impossible de charger les modèles texte-parole.", "Text-to-Speech-Modelle konnten nicht geladen werden.", "音声合成モデルを読み込めませんでした。", "텍스트-음성 모델을 불러올 수 없습니다.", "Não foi possível carregar os modelos de texto para voz."),
  "In use — uninstall another model to switch away from this one.": copy("In use — uninstall another model to switch away from this one.", "正在使用中——请卸载其他模型以切换。", "En uso: desinstala otro modelo para cambiar.", "En cours d’utilisation — désinstallez un autre modèle pour changer.", "In Verwendung — ein anderes Modell deinstallieren, um zu wechseln.", "使用中です。別のモデルをアンインストールして切り替えてください。", "사용 중 — 다른 모델을 제거하여 전환하세요.", "Em uso — desinstale outro modelo para mudar."),
  English: copy("English", "英语", "Inglés", "Anglais", "Englisch", "英語", "영어", "Inglês"),
  Chinese: copy("Chinese", "中文", "Chino", "Chinois", "Chinesisch", "中国語", "중국어", "Chinês"),
  Spanish: copy("Spanish", "西班牙语", "Español", "Espagnol", "Spanisch", "スペイン語", "스페인어", "Espanhol"),
  French: copy("French", "法语", "Francés", "Français", "Französisch", "フランス語", "프랑스어", "Francês"),
  German: copy("German", "德语", "Alemán", "Allemand", "Deutsch", "ドイツ語", "독일어", "Alemão"),
  Japanese: copy("Japanese", "日语", "Japonés", "Japonais", "Japanisch", "日本語", "일본어", "Japonês"),
  Korean: copy("Korean", "韩语", "Coreano", "Coréen", "Koreanisch", "韓国語", "한국어", "Coreano"),
  Portuguese: copy("Portuguese", "葡萄牙语", "Portugués", "Portugais", "Portugiesisch", "ポルトガル語", "포르투갈어", "Português"),
  Multilingual: copy("Multilingual", "多语言", "Multilingüe", "Multilingue", "Mehrsprachig", "多言語", "다국어", "Multilingue"),
  "Multiple voices": copy("Multiple voices", "多种音色", "Varias voces", "Plusieurs voix", "Mehrere Stimmen", "複数の音声", "여러 음성", "Várias vozes"),
  "English (US)": copy("English (US)", "英语（美国）", "Inglés (EE. UU.)", "Anglais (États-Unis)", "Englisch (USA)", "英語（米国）", "영어(미국)", "Inglês (EUA)"),
  "Spanish (Spain)": copy("Spanish (Spain)", "西班牙语（西班牙）", "Español (España)", "Espagnol (Espagne)", "Spanisch (Spanien)", "スペイン語（スペイン）", "스페인어(스페인)", "Espanhol (Espanha)"),
  "French (France)": copy("French (France)", "法语（法国）", "Francés (Francia)", "Français (France)", "Französisch (Frankreich)", "フランス語（フランス）", "프랑스어(프랑스)", "Francês (França)"),
  "German (Germany)": copy("German (Germany)", "德语（德国）", "Alemán (Alemania)", "Allemand (Allemagne)", "Deutsch (Deutschland)", "ドイツ語（ドイツ）", "독일어(독일)", "Alemão (Alemanha)"),
  "Portuguese (Brazil)": copy("Portuguese (Brazil)", "葡萄牙语（巴西）", "Portugués (Brasil)", "Portugais (Brésil)", "Portugiesisch (Brasilien)", "ポルトガル語（ブラジル）", "포르투갈어(브라질)", "Português (Brasil)"),
  "Portuguese (Portugal)": copy("Portuguese (Portugal)", "葡萄牙语（葡萄牙）", "Portugués (Portugal)", "Portugais (Portugal)", "Portugiesisch (Portugal)", "ポルトガル語（ポルトガル）", "포르투갈어(포르투갈)", "Português (Portugal)"),
  "Read aloud": copy("Read aloud", "朗读", "Leer en voz alta", "Lire à voix haute", "Vorlesen", "読み上げる", "소리 내어 읽기", "Ler em voz alta"),
  Stop: copy("Stop", "停止", "Detener", "Arrêter", "Stoppen", "停止", "중지", "Parar"),
  "Open Text-to-Speech Models": copy("Open Text-to-Speech Models", "打开文字转语音模型", "Abrir modelos de texto a voz", "Ouvrir les modèles texte-parole", "Text-to-Speech-Modelle öffnen", "音声合成モデルを開く", "텍스트-음성 모델 열기", "Abrir modelos de texto para voz"),
  "Available when the current local operation finishes.": copy("Available when the current local operation finishes.", "当前本地操作完成后即可使用。", "Disponible cuando finalice la operación local actual.", "Disponible une fois l’opération locale terminée.", "Verfügbar, sobald der aktuelle lokale Vorgang abgeschlossen ist.", "現在のローカル処理が完了すると使用できます。", "현재 로컬 작업이 완료되면 사용할 수 있습니다.", "Disponível quando a operação local atual terminar."),
  "There is no text to read aloud.": copy("There is no text to read aloud.", "没有可朗读的文字。", "No hay texto para leer en voz alta.", "Aucun texte à lire à voix haute.", "Kein Text zum Vorlesen vorhanden.", "読み上げるテキストがありません。", "소리 내어 읽을 텍스트가 없습니다.", "Não há texto para ler em voz alta."),
  "Wait for the current local AI or transcription operation to finish.": copy("Wait for the current local AI or transcription operation to finish.", "请等待当前本地 AI 或转写操作完成。", "Espera a que termine la operación local de IA o transcripción.", "Attendez la fin de l’opération locale d’IA ou de transcription.", "Warte, bis der aktuelle lokale KI- oder Transkriptionsvorgang abgeschlossen ist.", "現在のローカルAIまたは文字起こし処理が完了するまでお待ちください。", "현재 로컬 AI 또는 전사 작업이 완료될 때까지 기다려 주세요.", "Aguarde que a operação local de IA ou transcrição termine."),
  "Preparing speech…": copy("Preparing speech…", "正在准备语音……", "Preparando voz…", "Préparation de la voix…", "Sprachausgabe wird vorbereitet …", "音声を準備中…", "음성 준비 중…", "A preparar voz…"),
  Playing: copy("Playing", "正在播放", "Reproduciendo", "Lecture", "Wiedergabe", "再生中", "재생 중", "A reproduzir"),
  "Download and activate a TTS model first.": copy("Download and activate a TTS model first.", "请先下载并启用一个文字转语音模型。", "Descarga y activa primero un modelo de texto a voz.", "Téléchargez et activez d’abord un modèle texte-parole.", "Zuerst ein Text-to-Speech-Modell herunterladen und aktivieren.", "まず音声合成モデルをダウンロードして有効にしてください。", "먼저 텍스트-음성 모델을 다운로드하고 활성화하세요.", "Transfira e ative primeiro um modelo de texto para voz."),
  "Unable to start speech playback.": copy("Unable to start speech playback.", "无法开始语音播放。", "No se pudo iniciar la reproducción de voz.", "Impossible de démarrer la lecture vocale.", "Sprachwiedergabe konnte nicht gestartet werden.", "音声再生を開始できませんでした。", "음성 재생을 시작할 수 없습니다.", "Não foi possível iniciar a reprodução de voz."),
  "Speech playback failed.": copy("Speech playback failed.", "语音播放失败。", "Error en la reproducción de voz.", "Échec de la lecture vocale.", "Sprachwiedergabe fehlgeschlagen.", "音声再生に失敗しました。", "음성 재생에 실패했습니다.", "Falha na reprodução de voz."),
  "Regenerate Core Insights": copy("Regenerate Core Insights", "重新生成核心洞察", "Regenerar ideas principales", "Régénérer les analyses principales", "Kernerkenntnisse neu erzeugen", "コアインサイトを再生成", "핵심 인사이트 다시 생성", "Gerar novamente informações principais"),
  "Generate Core Insights": copy("Generate Core Insights", "生成核心洞察", "Generar ideas principales", "Générer les analyses principales", "Kernerkenntnisse erzeugen", "コアインサイトを生成", "핵심 인사이트 생성", "Gerar informações principais"),
  "Waiting for local AI…": copy("Waiting for local AI…", "正在等待本地 AI……", "Esperando a la IA local…", "En attente de l’IA locale…", "Warten auf lokale KI …", "ローカルAIを待機中…", "로컬 AI 대기 중…", "A aguardar pela IA local…"),
  "Extracting core insights…": copy("Extracting core insights…", "正在提取核心洞察……", "Extrayendo ideas principales…", "Extraction des analyses principales…", "Kernerkenntnisse werden extrahiert …", "コアインサイトを抽出中…", "핵심 인사이트 추출 중…", "A extrair informações principais…"),
  "Turn this transcript into a note shaped for how you'll use it.": copy("Turn this transcript into a note shaped for how you'll use it.", "根据你的使用场景，将转写内容整理成笔记。", "Convierte la transcripción en una nota adaptada a su uso.", "Transformez cette transcription en une note adaptée à votre usage.", "Dieses Transkript passend zum Verwendungszweck als Notiz strukturieren.", "用途に合わせて文字起こしをノートに整理します。", "사용 목적에 맞게 전사 내용을 노트로 정리하세요.", "Transforme a transcrição numa nota adaptada à sua utilização."),
  "Organizing your knowledge…": copy("Organizing your knowledge…", "正在整理知识……", "Organizando el conocimiento…", "Organisation de vos connaissances…", "Wissen wird organisiert …", "ナレッジを整理中…", "지식 정리 중…", "A organizar o conhecimento…"),
  "Running privately on this device. This can take a moment.": copy("Running privately on this device. This can take a moment.", "正在此设备上私密运行，可能需要一点时间。", "Se ejecuta de forma privada en este dispositivo. Puede tardar un momento.", "Exécution privée sur cet appareil. Cela peut prendre un moment.", "Private Ausführung auf diesem Gerät. Dies kann einen Moment dauern.", "この端末内で処理しています。少し時間がかかる場合があります。", "이 기기에서 비공개로 실행 중이며 잠시 걸릴 수 있습니다.", "Em execução privada neste dispositivo. Pode demorar um pouco."),
  "Choose a scene": copy("Choose a scene", "选择场景", "Elegir un escenario", "Choisir un scénario", "Szenario auswählen", "シーンを選択", "상황 선택", "Escolher um cenário"),
  Regenerate: copy("Regenerate", "重新生成", "Regenerar", "Régénérer", "Neu erzeugen", "再生成", "다시 생성", "Gerar novamente"),
  "Generate Knowledge": copy("Generate Knowledge", "生成知识", "Generar conocimiento", "Générer les connaissances", "Wissen erzeugen", "ナレッジを生成", "지식 생성", "Gerar conhecimento"),
  "Generate again": copy("Generate again", "再次生成", "Generar de nuevo", "Générer à nouveau", "Erneut erzeugen", "もう一度生成", "다시 생성", "Gerar novamente"),
  Meeting: copy("Meeting", "会议", "Reunión", "Réunion", "Besprechung", "会議", "회의", "Reunião"),
  Lecture: copy("Lecture", "讲座", "Clase", "Cours", "Vorlesung", "講義", "강의", "Aula"),
  Consultation: copy("Consultation", "咨询", "Consulta", "Consultation", "Beratung", "相談", "상담", "Consulta"),
  Interview: copy("Interview", "访谈", "Entrevista", "Entretien", "Interview", "インタビュー", "인터뷰", "Entrevista"),
  Brainstorm: copy("Brainstorm", "头脑风暴", "Lluvia de ideas", "Brainstorming", "Brainstorming", "ブレインストーミング", "브레인스토밍", "Brainstorming"),
  General: copy("General", "通用", "General", "Général", "Allgemein", "一般", "일반", "Geral"),
  "Discussion, decisions, alignment, tensions, and unresolved issues": copy("Discussion, decisions, alignment, tensions, and unresolved issues", "讨论、决策、共识、分歧和未解决问题", "Debate, decisiones, acuerdos, tensiones y asuntos pendientes", "Discussion, décisions, alignement, tensions et questions non résolues", "Diskussion, Entscheidungen, Abstimmung, Spannungen und offene Fragen", "議論、決定、合意、対立、未解決事項", "논의, 결정, 합의, 긴장 및 미해결 문제", "Discussão, decisões, alinhamento, tensões e questões por resolver"),
  "Concepts, explanations, examples, relationships, and caveats": copy("Concepts, explanations, examples, relationships, and caveats", "概念、讲解、示例、关联和注意事项", "Conceptos, explicaciones, ejemplos, relaciones y matices", "Concepts, explications, exemples, relations et réserves", "Konzepte, Erklärungen, Beispiele, Beziehungen und Einschränkungen", "概念、説明、例、関係、注意点", "개념, 설명, 예시, 관계 및 주의 사항", "Conceitos, explicações, exemplos, relações e ressalvas"),
  "Situation, professional guidance, rationale, options, and cautions": copy("Situation, professional guidance, rationale, options, and cautions", "情况、专业建议、依据、选项和注意事项", "Situación, orientación profesional, razones, opciones y precauciones", "Situation, conseils professionnels, justification, options et précautions", "Situation, fachliche Beratung, Begründung, Optionen und Hinweise", "状況、専門的助言、根拠、選択肢、注意事項", "상황, 전문 조언, 근거, 선택지 및 주의 사항", "Situação, orientação profissional, fundamentos, opções e cuidados"),
  "Perspectives, behavior, needs, motivations, and supported patterns": copy("Perspectives, behavior, needs, motivations, and supported patterns", "观点、行为、需求、动机和有依据的规律", "Perspectivas, comportamiento, necesidades, motivaciones y patrones respaldados", "Points de vue, comportement, besoins, motivations et tendances étayées", "Perspektiven, Verhalten, Bedürfnisse, Motivation und belegte Muster", "視点、行動、ニーズ、動機、裏付けられたパターン", "관점, 행동, 요구, 동기 및 근거 있는 패턴", "Perspetivas, comportamento, necessidades, motivações e padrões sustentados"),
  "Ideas, alternatives, connections, evaluation, and open questions": copy("Ideas, alternatives, connections, evaluation, and open questions", "想法、替代方案、关联、评估和开放问题", "Ideas, alternativas, conexiones, evaluación y preguntas abiertas", "Idées, alternatives, liens, évaluation et questions ouvertes", "Ideen, Alternativen, Verbindungen, Bewertung und offene Fragen", "アイデア、代替案、つながり、評価、未解決の質問", "아이디어, 대안, 연결, 평가 및 열린 질문", "Ideias, alternativas, ligações, avaliação e questões em aberto"),
  "Context, evidence, relationships, nuance, and reference details": copy("Context, evidence, relationships, nuance, and reference details", "背景、证据、关联、细节差异和参考信息", "Contexto, pruebas, relaciones, matices y detalles de referencia", "Contexte, éléments probants, relations, nuances et détails de référence", "Kontext, Belege, Beziehungen, Nuancen und Referenzdetails", "背景、根拠、関係、ニュアンス、参考情報", "맥락, 근거, 관계, 뉘앙스 및 참고 세부 정보", "Contexto, evidências, relações, nuances e detalhes de referência"),
};

const ZH_MODEL_DESCRIPTIONS: Record<string, string> = {
  "Llama 1B general-purpose multilingual instruction model for compact text generation.": "Llama 1B 通用多语言指令模型，适合轻量文本生成。",
  "Larger 3B instruction-tuned candidate from the multilingual Llama 3.2 family.": "来自多语言 Llama 3.2 系列的较大 3B 指令微调模型。",
  "Current-generation 1B multilingual Gemma instruction model for text generation.": "新一代 1B 多语言 Gemma 指令模型，用于文本生成。",
  "Microsoft's approximately 3.8B-parameter multilingual general instruction model.": "微软约 38 亿参数的多语言通用指令模型。",
  "LFM 1.2B general instruction model designed for compact and on-device deployment.": "LFM 1.2B 通用指令模型，专为轻量和设备端部署设计。",
  "High-resource 8B boundary candidate reserved for on-device feasibility testing.": "资源需求较高的 8B 边界候选模型，用于设备端可行性测试。",
  "Default multilingual model for broad language coverage.": "默认多语言模型，覆盖多种语言。",
  "Recommended Chinese model with compact INT8 weights and English support.": "推荐的中文模型，采用轻量 INT8 权重并支持英语。",
  "Full-precision Chinese and English alternative.": "全精度中英双语备选模型。",
  "Bilingual alternative based on the Matcha architecture.": "基于 Matcha 架构的双语备选模型。",
  "Dedicated Mandarin voice and the preferred compact Piper option.": "专用普通话音色，也是推荐的轻量 Piper 选项。",
  "Dedicated Mandarin backup voice.": "专用普通话备用音色。",
  "Compact US English voice with a good quality and speed balance.": "轻量美式英语音色，兼顾质量与速度。",
  "Higher-quality US English voice for devices with more storage.": "质量更高的美式英语音色，适合存储空间较大的设备。",
  "Dedicated Spanish voice.": "专用西班牙语音色。",
  "Dedicated French voice.": "专用法语音色。",
  "Compact dedicated German voice.": "轻量专用德语音色。",
  "Higher-quality German voice for devices with more storage.": "质量更高的德语音色，适合存储空间较大的设备。",
  "Dedicated Brazilian Portuguese voice.": "专用巴西葡萄牙语音色。",
  "Dedicated European Portuguese voice.": "专用欧洲葡萄牙语音色。",
};

export function translateUiCopy(value: string, language: UiLanguage): string {
  const exact = UI_COPY[value]?.[language];
  if (exact) return exact;

  if (language === "zh-CN") {
    const modelDescription = ZH_MODEL_DESCRIPTIONS[value];
    if (modelDescription) return modelDescription;

    const whisper = value.match(/^Multilingual Whisper (.+) speech recognition model \((.+)\)\.$/);
    if (whisper) return `多语言 Whisper ${whisper[1]} 语音识别模型（${whisper[2]}）。`;
    const parakeet = value.match(/^NVIDIA Parakeet TDT 0\.6B v3 speech recognition model \((.+)\)\.$/);
    if (parakeet) return `NVIDIA Parakeet TDT 0.6B v3 语音识别模型（${parakeet[1]}）。`;
  }

  const shown = value.match(/^(\d+) shown$/);
  if (shown) return ({ en: `${shown[1]} shown`, "zh-CN": `显示 ${shown[1]} 条`, es: `${shown[1]} mostradas`, fr: `${shown[1]} affichées`, de: `${shown[1]} angezeigt`, ja: `${shown[1]}件表示`, ko: `${shown[1]}개 표시`, pt: `${shown[1]} apresentadas` })[language];

  const thisWeek = value.match(/^\+(\S+) this week$/);
  if (thisWeek) return ({ en: `+${thisWeek[1]} this week`, "zh-CN": `本周 +${thisWeek[1]}`, es: `+${thisWeek[1]} esta semana`, fr: `+${thisWeek[1]} cette semaine`, de: `+${thisWeek[1]} diese Woche`, ja: `今週 +${thisWeek[1]}`, ko: `이번 주 +${thisWeek[1]}`, pt: `+${thisWeek[1]} esta semana` })[language];

  const completed = value.match(/^Completed \((\d+)\)$/);
  if (completed) return ({ en: `Completed (${completed[1]})`, "zh-CN": `已完成（${completed[1]}）`, es: `Completadas (${completed[1]})`, fr: `Terminées (${completed[1]})`, de: `Erledigt (${completed[1]})`, ja: `完了（${completed[1]}）`, ko: `완료됨 (${completed[1]})`, pt: `Concluídas (${completed[1]})` })[language];

  const downloading = value.match(/^Downloading…\s?(\d+)%$/);
  if (downloading) return ({ en: `Downloading… ${downloading[1]}%`, "zh-CN": `正在下载…… ${downloading[1]}%`, es: `Descargando… ${downloading[1]}%`, fr: `Téléchargement… ${downloading[1]}%`, de: `Wird heruntergeladen … ${downloading[1]}%`, ja: `ダウンロード中… ${downloading[1]}%`, ko: `다운로드 중… ${downloading[1]}%`, pt: `A transferir… ${downloading[1]}%` })[language];

  const removeModel = value.match(/^Remove "(.+)" from this device\?$/);
  if (removeModel) return ({ en: `Remove "${removeModel[1]}" from this device?`, "zh-CN": `要从此设备移除“${removeModel[1]}”吗？`, es: `¿Eliminar "${removeModel[1]}" de este dispositivo?`, fr: `Supprimer « ${removeModel[1]} » de cet appareil ?`, de: `„${removeModel[1]}“ von diesem Gerät entfernen?`, ja: `「${removeModel[1]}」をこの端末から削除しますか？`, ko: `이 기기에서 “${removeModel[1]}” 모델을 제거할까요?`, pt: `Remover "${removeModel[1]}" deste dispositivo?` })[language];

  const voices = value.match(/^(\d+) voice(s)?$/);
  if (voices) return ({ en: value, "zh-CN": `${voices[1]} 种音色`, es: `${voices[1]} ${voices[2] ? "voces" : "voz"}`, fr: `${voices[1]} voix`, de: `${voices[1]} Stimme${voices[2] ? "n" : ""}`, ja: `${voices[1]}音声`, ko: `${voices[1]}개 음성`, pt: `${voices[1]} ${voices[2] ? "vozes" : "voz"}` })[language];

  return value;
}
